// PURE DATA. No fs, no path, no traversal, no branching on runtime name.
// adapter-architecture §1.1: adding a surface is adding an object to an array.
//
// Full transcription of adapter-architecture §2.1 (discovery) crossed with §2.2
// (semantics), amended by spike-corrections §7.2 (secret_positions split) and §7.3
// (hooks[].command is argv, not an unconditional redaction position).
//
// M2 carried §7.3 to the two other command-valued keys: `apiKeyHelper` and
// `awsCredentialExport` name a PROGRAM that prints a credential, not a credential. They
// were listed in both secret_positions and argv_positions; unconditional redaction there
// destroys the command, which is the portable content, so they are argv-only now.
//
// Constraints the data cannot express:
//  - `tokens` is expanded in declaration order. `${root:<root_id>}` resolves to that
//    root's platform-selected path; a flat token table cannot carry a per-platform
//    value, and CLAUDE_MANAGED is different on darwin/linux/win32 (CLA §6.1).
//  - `${CLAUDE_CONFIG_DIR}` is an environment variable, not a token, so the
//    CLAUDE_HOME default expansion is not self-referential.
//  - Identity template `{0}` on a file-backed location is the wildcard capture from
//    the location's path glob (the same convention key_path patterns use). Only
//    claude.skills.plugin needs it.

export default {
  id: "claude",
  display_name: "Claude Code",
  status: "supported",
  adapter_version: "1.0.0",

  detect: {
    present_if: [{ kind: "dir_exists", path: "${CLAUDE_HOME}" }],
    version: [
      { kind: "file_key", path: "${HOME}/.claude.json", key_path: "installMethod", parse: "string" },
    ],
    version_required: false,
    breaking_below: null,
  },

  tokens: {
    CLAUDE_HOME: "${CLAUDE_CONFIG_DIR:-${HOME}/.claude}",
    CLAUDE_MANAGED: "${root:claude_managed}",
  },

  roots: [
    { root_id: "claude_home", scope: "user", path: "${CLAUDE_CONFIG_DIR:-${HOME}/.claude}", declared: true },
    { root_id: "home", scope: "user", path: "${HOME}", declared: true },
    { root_id: "project", scope: "project", path: "${PROJECT}", declared: true },
    {
      root_id: "claude_managed",
      scope: "managed",
      platform: {
        darwin: "/Library/Application Support/ClaudeCode",
        linux: "/etc/claude-code",
        win32: "C:\\Program Files\\ClaudeCode",
      },
      declared: true,
    },
  ],

  // manifest §3.2 — layer_id is `<runtime>/<scope>`; rank carries precedence.
  // CLA §6.1: managed > CLI args > local > project > user.
  layer_ranks: { managed: 100, cli: 90, local: 80, project: 70, user: 60, plugin: 40 },

  project_markers: [".claude", "CLAUDE.md", ".git"],

  // CLA §3.4, §7.4 — project `permissions.allow` and `additionalDirectories` sit behind
  // the trust dialog. Read locally so the report can explain a suppressed layer; on the
  // never-export table (claude.trust_state) so it can never be carried to another
  // machine, where it would pre-trust a repository the target user never accepted.
  project_trust: {
    source_id: "claude.store",
    container_key: "projects",
    key: "hasTrustDialogAccepted",
    trusted_values: [true],
    default_untrusted: false,
    evidence: "CLA §3.4/§7.4 — .claude.json projects[<abs>].hasTrustDialogAccepted",
  },

  // THR §3.2 Layer 2 — curated, and shown in the report so the user can see what we
  // chose NOT to redact. CLA §6.2: this is a feature flag, not a credential.
  secret_key_allowlist: ["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"],

  // Files the scanner opens once; embedded surfaces address key paths inside them.
  sources: [
    {
      source_id: "claude.settings.managed.file",
      scope: "managed",
      root_id: "claude_managed",
      path: "${CLAUDE_MANAGED}/managed-settings.json",
      format: "json",
      label: "managed-settings.json",
    },
    {
      source_id: "claude.settings.user.file",
      scope: "user",
      root_id: "claude_home",
      path: "${CLAUDE_HOME}/settings.json",
      format: "json",
      label: "~/.claude/settings.json",
    },
    {
      source_id: "claude.settings.project.file",
      scope: "project",
      root_id: "project",
      path: "${PROJECT}/.claude/settings.json",
      format: "json",
      label: "${PROJECT}/.claude/settings.json",
    },
    {
      source_id: "claude.settings.local.file",
      scope: "local",
      root_id: "project",
      path: "${PROJECT}/.claude/settings.local.json",
      format: "json",
      label: "${PROJECT}/.claude/settings.local.json",
    },
    {
      source_id: "claude.store",
      scope: "user",
      root_id: "home",
      path: "${HOME}/.claude.json",
      format: "json",
      label: "~/.claude.json",
    },
    {
      source_id: "claude.mcp.project.file",
      scope: "project",
      root_id: "project",
      path: "${PROJECT}/.mcp.json",
      format: "json",
      label: "${PROJECT}/.mcp.json",
    },
    {
      source_id: "claude.mcp.managed.file",
      scope: "managed",
      root_id: "claude_managed",
      path: "${CLAUDE_MANAGED}/managed-mcp.json",
      format: "json",
      label: "managed-mcp.json",
    },
    {
      source_id: "claude.plugins.hooks.file",
      scope: "plugin",
      root_id: "claude_home",
      path: "${CLAUDE_HOME}/plugins/cache/*/*/*/hooks/hooks.json",
      format: "json",
      label: "~/.claude/plugins/cache/<mkt>/<plugin>/<version>/hooks/hooks.json",
    },
    {
      source_id: "claude.plugins.installed.file",
      scope: "user",
      root_id: "claude_home",
      path: "${CLAUDE_HOME}/plugins/installed_plugins.json",
      format: "json",
      label: "~/.claude/plugins/installed_plugins.json",
    },
    {
      source_id: "claude.marketplaces.file",
      scope: "user",
      root_id: "claude_home",
      path: "${CLAUDE_HOME}/plugins/known_marketplaces.json",
      format: "json",
      label: "~/.claude/plugins/known_marketplaces.json",
    },
  ],

  surfaces: [
    // ── instructions ────────────────────────────────────────────────────────
    {
      surface_id: "claude.instructions.managed",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.1 — managed policy CLAUDE.md; verified absent on the surveyed machine (both macOS and Linux paths)",
      locations: [
        { scope: "managed", root_id: "claude_managed", path: "${CLAUDE_MANAGED}/CLAUDE.md", match: "file" },
      ],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: null, write_mode: "none", post_import_note: "org-owned policy layer; Continuity never writes it" },
      notes: "Org-owned. Read for the effective view and never emitted. CLA §9: the managed CLAUDE.md can never be excluded by claudeMdExcludes.",
    },
    {
      surface_id: "claude.instructions.user",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.1 — ~/.claude/CLAUDE.md present, 3344 B on the surveyed machine",
      locations: [{ scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/CLAUDE.md", match: "file" }],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "PORTABLE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_HOME}" }],
      },
      trust_tier: "INERT",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "body", detector: "existing_dotfile_path" }],
      emit: { target: "${CLAUDE_HOME}/CLAUDE.md", write_mode: "create_file" },
      notes: "Instruction bodies are inert to the OS but executed by the agent every session (THR T-I6); the import diff always renders full text.",
    },
    {
      surface_id: "claude.instructions.project",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.2 — ./CLAUDE.md present (6658 B); the .claude/CLAUDE.md variant is documented but absent everywhere on the surveyed machine",
      locations: [
        {
          scope: "project",
          root_id: "project",
          path: "${PROJECT}/CLAUDE.md",
          match: "file",
          ancestor_walk: "root_to_cwd",
          at_most_one_per_dir: false,
        },
        {
          scope: "project",
          root_id: "project",
          path: "${PROJECT}/.claude/CLAUDE.md",
          match: "file",
          ancestor_walk: "root_to_cwd",
          at_most_one_per_dir: false,
        },
      ],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "body", detector: "existing_dotfile_path" }],
      emit: { target: "${PROJECT}/CLAUDE.md", write_mode: "create_file" },
      notes: "Root-down ancestor walk; later text has more influence (CLA §1.2). Subdirectory files BELOW cwd are not loaded at launch, so they are scanned but marked applied: false with reason 'lazy — loads when a file in that directory is read'.",
    },
    {
      surface_id: "claude.instructions.local",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.1 — ./CLAUDE.local.md documented, absent on the surveyed machine (scoped find, no hits)",
      locations: [
        {
          scope: "local",
          root_id: "project",
          path: "${PROJECT}/CLAUDE.local.md",
          match: "file",
          ancestor_walk: "root_to_cwd",
          at_most_one_per_dir: false,
        },
      ],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: "${PROJECT}/CLAUDE.local.md", write_mode: "create_file" },
      notes: "CLA §1.2 — appended AFTER that directory's CLAUDE.md, which is why at_most_one_per_dir is false. Codex has no equivalent personal-project layer.",
    },
    {
      surface_id: "claude.rules.user",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.5 — ~/.claude/rules/*.md documented; absent on the surveyed machine (§6.4 ls, no hit)",
      locations: [
        { scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/rules", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: ["paths"],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      caps: { max_bytes: 4194304 },
      emit: { target: "${CLAUDE_HOME}/rules/{identity}", write_mode: "create_file" },
      notes: "CLA §1.5 — rules without `paths` load unconditionally at the same priority as .claude/CLAUDE.md. Brace expansion budget: 1,000 expanded patterns / 4 MiB per rule. The `paths` frontmatter has no Codex analogue.",
    },
    {
      surface_id: "claude.rules.project",
      kind: "instructions",
      confidence: "high",
      evidence: "CLA §1.5 — .claude/rules/*.md, recursive; absent on the surveyed machine",
      locations: [
        { scope: "project", root_id: "project", path: "${PROJECT}/.claude/rules", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: ["paths"],
      merge: {
        algebra: "concatenate",
        group: "claude.instructions",
        effective_key: "chain",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      caps: { max_bytes: 4194304 },
      emit: { target: "${PROJECT}/.claude/rules/{identity}", write_mode: "create_file" },
      notes: "Symlinked rule files and directories are resolved and loaded; circular symlinks are handled by the runtime (CLA §1.5). Continuity still applies the three-outcome symlink policy (THR §3.1).",
    },

    // ── skills and commands ─────────────────────────────────────────────────
    {
      surface_id: "claude.skills.user",
      kind: "skill",
      confidence: "high",
      evidence: "CLA §2.1, §2.2, §2.4 — 80 skills, 1.1 GB on the surveyed machine",
      locations: [
        { scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/skills", match: "dir_of", glob: "*/SKILL.md", depth: 2 },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: [
        "name",
        "description",
        "when_to_use",
        "argument-hint",
        "arguments",
        "disable-model-invocation",
        "user-invocable",
        "allowed-tools",
        "disallowed-tools",
        "model",
        "effort",
        "context",
        "agent",
        "background",
        "hooks",
        "paths",
        "shell",
      ],
      assets: {
        globs: ["**/*"],
        payload_policy_aware: true,
        roles: {
          "scripts/**": "script",
          "lib/**": "script",
          "bin/**": "script",
          "references/**": "reference",
          "*.md": "reference",
        },
      },
      merge: {
        algebra: "coexist",
        group: "claude.skills",
        effective_key: "identity",
        layer_order: ["claude/plugin", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "PORTABLE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_SKILL_DIR}" }],
      },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${CLAUDE_HOME}/skills/{identity}/",
        write_mode: "relocate_dir",
        disabled_form: { mode: "companion_key", surface_id: "claude.settings.user", key_path: "skillOverrides.{identity}", value: "off" },
      },
      caps: { max_bytes: 1048576 },
      notes: "Trust escalates to EXECUTABLE when an asset carries the exec bit (kinds.js maxTier; escalation only). Command name comes from the DIRECTORY, not frontmatter `name` (CLA §2.4). Same-name precedence across scopes is UNKNOWN (CLA §12.1) — coexist is the safe default. 20+ undocumented frontmatter keys are the norm (CLA §2.3): everything outside recognized_keys round-trips verbatim in payload.unrecognized.",
    },
    {
      surface_id: "claude.skills.project",
      kind: "skill",
      confidence: "high",
      evidence: "CLA §2.1 — <project>/.claude/skills/<name>/SKILL.md documented; absent in every project on the surveyed machine",
      locations: [
        { scope: "project", root_id: "project", path: "${PROJECT}/.claude/skills", match: "dir_of", glob: "*/SKILL.md", depth: 2 },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: [
        "name",
        "description",
        "when_to_use",
        "argument-hint",
        "arguments",
        "disable-model-invocation",
        "user-invocable",
        "allowed-tools",
        "disallowed-tools",
        "model",
        "effort",
        "context",
        "agent",
        "background",
        "hooks",
        "paths",
        "shell",
      ],
      assets: {
        globs: ["**/*"],
        payload_policy_aware: true,
        roles: { "scripts/**": "script", "lib/**": "script", "bin/**": "script", "references/**": "reference", "*.md": "reference" },
      },
      merge: {
        algebra: "coexist",
        group: "claude.skills",
        effective_key: "identity",
        layer_order: ["claude/plugin", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "PORTABLE",
        rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${CLAUDE_PROJECT_DIR}" }],
      },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${PROJECT}/.claude/skills/{identity}/",
        write_mode: "relocate_dir",
        disabled_form: { mode: "companion_key", surface_id: "claude.settings.user", key_path: "skillOverrides.{identity}", value: "off" },
      },
      caps: { max_bytes: 1048576 },
      notes: "CLA §2.4 — a project skill's `allowed-tools` only takes effect after the workspace trust dialog is accepted, so a project-scope import can look inert until the user trusts the workspace (manifest §5.4 limits v1 imports to user scope for exactly this reason).",
    },
    {
      surface_id: "claude.skills.plugin",
      kind: "skill",
      confidence: "high",
      evidence: "CLA §2.1 — plugin skills at <plugin>/skills/<name>/SKILL.md or a bare SKILL.md at plugin root; the posthog plugin ships ~130 on the surveyed machine",
      locations: [
        {
          scope: "plugin",
          root_id: "claude_home",
          path: "${CLAUDE_HOME}/plugins/cache/*/*/*/skills",
          match: "dir_of",
          glob: "*/SKILL.md",
          depth: 2,
        },
        {
          scope: "plugin",
          root_id: "claude_home",
          path: "${CLAUDE_HOME}/plugins/cache/*/*/*",
          match: "dir_of",
          glob: "SKILL.md",
          depth: 1,
        },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "composite", field: "name", template: "{0}:{dirname}" },
      recognized_keys: ["name", "description", "when_to_use", "argument-hint", "allowed-tools", "disallowed-tools", "model", "hooks", "paths"],
      assets: { globs: ["**/*"], payload_policy_aware: true, roles: { "scripts/**": "script", "*.md": "reference" } },
      merge: {
        algebra: "coexist",
        group: "claude.skills",
        effective_key: "identity",
        layer_order: ["claude/plugin", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "DERIVED", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: null,
        write_mode: "none",
        post_import_note: "port the plugin DECLARATION (enabledPlugins + known_marketplaces), never the cache — the payload is re-resolvable from the marketplace",
      },
      notes: "CLA §2.4 — a plugin skill's last command segment comes from frontmatter `name` OR the directory name, prefixed with the plugin id: identity template is `{0}:{dirname}`, where `{0}` is the plugin-directory wildcard capture from the location path glob. DERIVED because ~/.claude/plugins/cache is 56 MB of re-downloadable content (CLA §8.2).",
    },
    {
      surface_id: "claude.commands.user",
      kind: "command",
      confidence: "high",
      evidence: "CLA §2.1 — ~/.claude/commands/ documented and merged into skills; verified absent on the surveyed machine (§6.4 ls)",
      locations: [
        { scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/commands", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: ["name", "description", "argument-hint", "arguments", "allowed-tools", "disallowed-tools", "model", "disable-model-invocation"],
      merge: {
        algebra: "coexist",
        group: "claude.commands",
        effective_key: "identity",
        layer_order: ["claude/plugin", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/commands/{identity}", write_mode: "create_file" },
      notes: "CLA §2.1 — commands were merged into skills: .claude/commands/deploy.md and .claude/skills/deploy/SKILL.md both produce /deploy with the same frontmatter, so an importer can normalise legacy commands into skill directories losslessly.",
    },
    {
      surface_id: "claude.commands.project",
      kind: "command",
      confidence: "high",
      evidence: "CLA §2.1 — .claude/commands/<name>.md; present inside the posthog plugin on the surveyed machine, absent at user/project scope",
      locations: [
        { scope: "project", root_id: "project", path: "${PROJECT}/.claude/commands", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: ["name", "description", "argument-hint", "arguments", "allowed-tools", "disallowed-tools", "model", "disable-model-invocation"],
      merge: {
        algebra: "coexist",
        group: "claude.commands",
        effective_key: "identity",
        layer_order: ["claude/plugin", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: "${PROJECT}/.claude/commands/{identity}", write_mode: "create_file" },
      notes: "Nested command directories are flattened by the Codex prompts target (COD §4.6); the default cross-runtime target is a Codex SKILL, which keeps repo scope and nesting.",
    },

    // ── MCP servers ─────────────────────────────────────────────────────────
    {
      surface_id: "claude.mcp.user",
      kind: "mcp_server",
      confidence: "high",
      evidence: "CLA §3.1, §3.3 — ~/.claude.json top-level mcpServers; 2 entries on the surveyed machine, one carrying a plaintext 51-char API key",
      locations: [{ scope: "user", source_id: "claude.store", key_path: "mcpServers.*", match: "embedded" }],
      claims: ["mcpServers.**"],
      embedded_in: { surface_id: "claude.store", key_path: "mcpServers.<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["type", "command", "args", "env", "url", "headers", "headersHelper", "timeout", "alwaysLoad"],
      merge: {
        algebra: "override_whole_entry",
        group: "claude.mcp",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*", "headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: {
        class: "SECRET",
        rewrites: [
          { rewrite_id: "env_to_reference", detector: "positional", target: "env_vars[] | bearer_token_env_var | env_http_headers" },
          { rewrite_id: "abs_path", detector: "path.absolute_home", target: "${HOME}" },
        ],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path" }],
      emit: {
        target: "${HOME}/.claude.json",
        write_mode: "merge_key",
        disabled_form: { mode: "in_entry", key_path: "disabled", value: true },
        post_import_note: "stdio servers execute a local binary; enabling is a second explicit action",
      },
      notes: "EXECUTABLE when `command` is present, DECLARATIVE when the entry is remote-only (`url`). Fields never merge across scopes — the highest-precedence source supplies the whole entry (CLA §3.1). `${VAR}` / `${VAR:-default}` expansion applies to command, args, env, url and headers; an unset variable warns and passes the literal through (CLA §3.2).",
    },
    {
      surface_id: "claude.mcp.local",
      kind: "mcp_server",
      confidence: "high",
      evidence: "CLA §3.1 — ~/.claude.json projects[\"<abs path>\"].mcpServers is the default (local) scope; all 16 project entries carry the key on the surveyed machine",
      locations: [{ scope: "local", source_id: "claude.store", key_path: "projects.*.mcpServers.*", match: "embedded" }],
      claims: ["projects.*.mcpServers.**"],
      embedded_in: { surface_id: "claude.store", key_path: "projects[\"<abs>\"].mcpServers.<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{1}" },
      // The first capture IS the project's absolute path, so the item belongs to that
      // project rather than to the user-scope file it happens to be stored in.
      project_from: { capture: 0 },
      recognized_keys: ["type", "command", "args", "env", "url", "headers", "headersHelper", "timeout", "alwaysLoad"],
      merge: {
        algebra: "override_whole_entry",
        group: "claude.mcp",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*", "headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: {
        class: "SECRET",
        rewrites: [
          { rewrite_id: "env_to_reference", detector: "positional", target: "env_vars[] | bearer_token_env_var | env_http_headers" },
          { rewrite_id: "project_key", detector: "path.absolute_home", target: "${PROJECT}" },
        ],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path" }],
      emit: {
        target: "${HOME}/.claude.json",
        write_mode: "merge_key",
        disabled_form: { mode: "in_entry", key_path: "disabled", value: true },
      },
      notes: "The project key is an ABSOLUTE path, so it must be re-derived on the target (manifest §1.1). CLA §8.3: the projects[] list is also stale on the surveyed machine — reconcile against the filesystem, never trust the list. Identity capture {1} is the server name; {0} is the project path.",
    },
    {
      surface_id: "claude.mcp.project",
      kind: "mcp_server",
      confidence: "high",
      evidence: "CLA §3.1 — .mcp.json at project root is the team-shared scope; no .mcp.json exists in any project on the surveyed machine, the posthog plugin ships one",
      locations: [{ scope: "project", source_id: "claude.mcp.project.file", key_path: "mcpServers.*", match: "embedded" }],
      claims: ["mcpServers.**"],
      embedded_in: { surface_id: "claude.mcp.project.file", key_path: "mcpServers.<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["type", "command", "args", "env", "url", "headers", "headersHelper", "timeout", "alwaysLoad"],
      merge: {
        algebra: "override_whole_entry",
        group: "claude.mcp",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*", "headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: {
        class: "SECRET",
        rewrites: [{ rewrite_id: "env_to_reference", detector: "positional", target: "env_vars[] | bearer_token_env_var | env_http_headers" }],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path" }],
      emit: {
        target: "${PROJECT}/.mcp.json",
        write_mode: "merge_key",
        disabled_form: { mode: "in_entry", key_path: "disabled", value: true },
        post_import_note: "never pre-approve an imported .mcp.json server: enableAllProjectMcpServers and enabledMcpjsonServers are ignored until the workspace trust dialog is accepted (CLA §3.4), and pre-approving would defeat a deliberate supply-chain control",
      },
      notes: "CLA §3.1 — plugins and connectors match duplicates by ENDPOINT (same URL/command), while the three file scopes match by name. `${CLAUDE_PROJECT_DIR}` is set in the server's environment, not Claude's, so in .mcp.json it needs a default: ${CLAUDE_PROJECT_DIR:-.}.",
    },
    {
      surface_id: "claude.mcp.settings",
      kind: "mcp_server",
      confidence: "low",
      evidence: "discovery.js:399-401 — the shipped CLI reads mcpServers out of .claude/settings{,.local}.json; the key is absent from CLA §3.1's storage table",
      locations: [
        { scope: "project", source_id: "claude.settings.project.file", key_path: "mcpServers.*", match: "embedded" },
        { scope: "local", source_id: "claude.settings.local.file", key_path: "mcpServers.*", match: "embedded" },
      ],
      claims: ["mcpServers.**"],
      embedded_in: { surface_id: "claude.settings.project.file", key_path: "mcpServers.<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["type", "command", "args", "env", "url", "headers", "timeout"],
      merge: {
        algebra: "override_whole_entry",
        group: "claude.mcp",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*", "headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: { class: "SECRET", rewrites: [] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      emit: { target: null, write_mode: "none" },
      notes: "CONFIDENCE LOW, and this is why: the current CLI reads this position but the documentation does not list it as an MCP storage location (manifest §9.2). Declared so a real entry is never silently dropped; emit is `none` in both directions until the position is confirmed, because writing to an undocumented position could produce config the runtime ignores.",
    },
    {
      surface_id: "claude.mcp.managed",
      kind: "mcp_server",
      confidence: "high",
      evidence: "CLA §3.1 — managed-mcp.json in the managed settings dir is the org-wide scope; verified absent on the surveyed machine (CLA §12.7, managed layer is doc-only)",
      locations: [{ scope: "managed", source_id: "claude.mcp.managed.file", key_path: "mcpServers.*", match: "embedded" }],
      claims: ["mcpServers.**"],
      embedded_in: { surface_id: "claude.mcp.managed.file", key_path: "mcpServers.<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["type", "command", "args", "env", "url", "headers", "timeout"],
      merge: {
        algebra: "override_whole_entry",
        group: "claude.mcp",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*", "headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      emit: { target: null, write_mode: "none", post_import_note: "org-owned; Continuity reads it for the effective view and never writes it" },
      notes: "Everything in CLA §6.1 about the managed layer is doc-only and untested (CLA §12.7); the surface is declared so an org-managed machine is described rather than silently missing a layer.",
    },

    // ── hooks ───────────────────────────────────────────────────────────────
    {
      surface_id: "claude.hooks.settings",
      kind: "hook",
      confidence: "high",
      evidence: "CLA §4.1–4.5 — 2 Stop hooks with absolute paths on the surveyed machine",
      locations: [
        { scope: "managed", source_id: "claude.settings.managed.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "local", source_id: "claude.settings.local.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "project", source_id: "claude.settings.project.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "user", source_id: "claude.settings.user.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
      ],
      claims: ["hooks.**"],
      embedded_in: { surface_id: "claude.settings.user.file", key_path: "hooks.<Event>[i].hooks[j]" },
      format: "json",
      container: "embedded",
      identity: { from: "composite", template: "{0}.{1}.{2}" },
      recognized_keys: ["type", "command", "args", "timeout", "async", "shell", "if", "once"],
      merge: {
        algebra: "aggregate",
        group: "claude.hooks",
        effective_key: "capture:0",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: {
        class: "REWRITE",
        rewrites: [
          { rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_PROJECT_DIR}|${CLAUDE_HOME}" },
        ],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [
        { rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" },
        { rel: "gated_by", from: "body", detector: "existing_dotfile_path" },
      ],
      emit: {
        target: "${CLAUDE_HOME}/settings.json",
        write_mode: "merge_key",
        disabled_form: { mode: "relocate_key", key_path: "hooks_disabled" },
        post_import_note: "hooks import disabled; enabling is a second explicit action",
      },
      notes: "Aggregate, not override — every matching hook from every source runs (CLA §4.1). Identity is the three key-path captures Event.i.j; the design doc's four-part <Event>:<matcher>:<i>:<j> form cannot be produced from the key path alone because `matcher` is a sibling VALUE, not a capture — it is preserved in payload and rendered in the report. A hook's behaviour is not fully described by settings: sibling files (the .quiet sentinel) can mute it (CLA §4.4), carried as a `gated_by` edge.",
    },
    {
      surface_id: "claude.hooks.plugin",
      kind: "hook",
      confidence: "high",
      evidence: "CLA §4.4 — the posthog plugin's hooks/hooks.json demonstrates the portable ${CLAUDE_PLUGIN_ROOT} idiom on the surveyed machine",
      locations: [
        { scope: "plugin", source_id: "claude.plugins.hooks.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
      ],
      claims: ["hooks.**"],
      embedded_in: { surface_id: "claude.plugins.hooks.file", key_path: "hooks.<Event>[i].hooks[j]" },
      format: "json",
      container: "embedded",
      identity: { from: "composite", template: "{0}.{1}.{2}" },
      recognized_keys: ["type", "command", "args", "timeout", "async", "shell", "if", "once"],
      merge: {
        algebra: "aggregate",
        group: "claude.hooks",
        effective_key: "capture:0",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user", "claude/plugin"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: { class: "DERIVED", rewrites: [] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" }],
      emit: {
        target: null,
        write_mode: "none",
        post_import_note: "plugin hooks arrive with the plugin; port the enabledPlugins declaration instead",
      },
      notes: "DERIVED: the hook lives inside ~/.claude/plugins/cache, which is re-resolvable from the marketplace (CLA §8.2). Plugin subagents ignore hooks/mcpServers/permissionMode (CLA §8.1), and pluginConfigs is ignored in project/local settings since v2.1.207 so a cloned repo cannot inject values into plugin hook commands.",
    },
    {
      surface_id: "claude.hooks.frontmatter",
      kind: "hook",
      confidence: "high",
      evidence: "CLA §4.1 — skill and agent frontmatter carry a `hooks:` field; 8 of 1,423 SKILL.md files use it (CLA §2.3)",
      locations: [
        { match: "derived_from", surface_id: "claude.skills.user", position: "frontmatter.hooks" },
        { match: "derived_from", surface_id: "claude.skills.project", position: "frontmatter.hooks" },
        { match: "derived_from", surface_id: "claude.subagents.user", position: "frontmatter.hooks" },
        { match: "derived_from", surface_id: "claude.subagents.project", position: "frontmatter.hooks" },
      ],
      claims: ["hooks.**"],
      embedded_in: { surface_id: "claude.skills.user", key_path: "hooks.<Event>[i].hooks[j]" },
      format: "yaml",
      container: "embedded",
      identity: { from: "composite", template: "{0}.{1}.{2}" },
      recognized_keys: ["type", "command", "args", "timeout", "async", "shell", "if", "once"],
      merge: {
        algebra: "aggregate",
        group: "claude.hooks",
        effective_key: "capture:0",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_SKILL_DIR}" }] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" }],
      emit: {
        target: null,
        write_mode: "none",
        post_import_note: "these hooks travel inside their skill or agent file; they are never written separately",
      },
      notes: "Skill-lifecycle-scoped: the hook is a key inside a frontmatter block that a different surface already carries, so it is addressed as a derived view (position `frontmatter.hooks`, the sibling of `command` in the derived_from position set) and emitted only with its parent. Codex has no frontmatter-hook position at all.",
    },
    {
      surface_id: "claude.hook_scripts",
      kind: "hook_script",
      confidence: "high",
      evidence: "CLA §4.4/§4.5 — notify-say.sh (1350 B, mode 755) and copy-final-to-clipboard.sh (1197 B, mode 755) on the surveyed machine; a hook config without its script is a broken config (THR B2)",
      locations: [
        { match: "derived_from", surface_id: "claude.hooks.settings", position: "command" },
        { match: "derived_from", surface_id: "claude.hooks.plugin", position: "command" },
        { match: "derived_from", surface_id: "claude.hooks.frontmatter", position: "command" },
      ],
      format: "binary",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: { algebra: "coexist", group: "claude.hook_scripts", effective_key: "identity" },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_HOME}" }],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "gated_by", from: "body", detector: "existing_dotfile_path" }],
      emit: {
        target: "${CLAUDE_HOME}/hooks/{identity}",
        write_mode: "create_file",
        disabled_form: { mode: "no_exec_bit", file_mode: 384 },
        post_import_note: "written without the exec bit; the user sets it as a second explicit action after reading the body",
      },
      caps: { max_bytes: 1048576 },
      notes: "Carried so an imported hook is not a dangling reference. Format is `binary` because the script may be any interpreter or a compiled file; the body is shown in full before import (THR §5.2, INERT/EXECUTABLE consent table).",
    },

    // ── subagents and memory ────────────────────────────────────────────────
    {
      surface_id: "claude.subagents.user",
      kind: "subagent",
      confidence: "high",
      evidence: "CLA §8.1 — 7 agents in ~/.claude/agents/ on the surveyed machine, bodies embedding absolute /Users/... paths",
      locations: [
        { scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/agents", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "field", field: "name", template: "{field}" },
      recognized_keys: [
        "name",
        "description",
        "tools",
        "disallowedTools",
        "model",
        "skills",
        "hooks",
        "memory",
        "background",
        "effort",
        "isolation",
        "color",
        "permissionMode",
        "mcpServers",
      ],
      merge: {
        algebra: "override",
        group: "claude.subagents",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/cli", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${HOME}" }],
      },
      trust_tier: "DECLARATIVE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "body", detector: "existing_dotfile_path" }],
      emit: { target: "${CLAUDE_HOME}/agents/{identity}.md", write_mode: "create_file" },
      notes: "Identity comes ONLY from the `name` field, not the path (CLA §8.1); the tree is scanned recursively and duplicate names in one directory are undefined (filesystem read order). Trust is DECLARATIVE + INERT body: the markdown is inert to the OS but drives the agent. `name` may not contain `:` as of v2.1.218.",
    },
    {
      surface_id: "claude.subagents.project",
      kind: "subagent",
      confidence: "high",
      evidence: "CLA §8.1 — project .claude/agents/ outranks user scope; nested project dirs resolve closest-to-cwd first",
      locations: [
        { scope: "project", root_id: "project", path: "${PROJECT}/.claude/agents", match: "glob", glob: "**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "field", field: "name", template: "{field}" },
      recognized_keys: [
        "name",
        "description",
        "tools",
        "disallowedTools",
        "model",
        "skills",
        "hooks",
        "memory",
        "background",
        "effort",
        "isolation",
        "color",
        "permissionMode",
        "mcpServers",
      ],
      merge: {
        algebra: "override",
        group: "claude.subagents",
        effective_key: "identity",
        layer_order: ["claude/managed", "claude/cli", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${CLAUDE_PROJECT_DIR}" }],
      },
      trust_tier: "DECLARATIVE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "body", detector: "existing_dotfile_path" }],
      emit: { target: "${PROJECT}/.claude/agents/{identity}.md", write_mode: "create_file" },
      notes: "Same identity rule as user scope. A `memory:` field pulls in three more directories (claude.agent_memory), so a subagent import that skips agent-memory changes behaviour.",
    },
    {
      surface_id: "claude.agent_memory",
      kind: "memory",
      confidence: "high",
      evidence: "CLA §8.1 — ~/.claude/agent-memory/<name>/, .claude/agent-memory/<name>/ and .claude/agent-memory-local/<name>/; none exist on the surveyed machine (no agent uses `memory:`)",
      locations: [
        { scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/agent-memory", match: "glob", glob: "*/**/*.md" },
        { scope: "project", root_id: "project", path: "${PROJECT}/.claude/agent-memory", match: "glob", glob: "*/**/*.md" },
        { scope: "local", root_id: "project", path: "${PROJECT}/.claude/agent-memory-local", match: "glob", glob: "*/**/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "composite", template: "{dirname}/{basename}" },
      recognized_keys: ["name", "description", "metadata", "type", "originSessionId"],
      merge: { algebra: "coexist", group: "claude.memory", effective_key: "identity" },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${HOME}" }],
      },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/agent-memory/{identity}", write_mode: "create_file" },
      notes: "Keyed by agent name (the immediate parent directory), which is why identity is <agent>/<basename>. The `-local` variant is the gitignored personal layer.",
    },
    {
      surface_id: "claude.memory.auto",
      kind: "memory",
      confidence: "high",
      evidence: "CLA §5.1 — 4 of 24 project directories contain memory/, 130 files total on the surveyed machine",
      locations: [
        { scope: "project", root_id: "claude_home", path: "${CLAUDE_HOME}/projects", match: "glob", glob: "*/memory/*.md" },
      ],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      // The first relpath segment is the munged project directory. It is matched by
      // re-encoding each known project forward; the encoding is never inverted, because
      // its character class is UNKNOWN beyond `/`, `.` and space (CLA §12.2).
      project_from: { relpath_segment: 0, encoding: "path_separators_to_dash" },
      recognized_keys: ["name", "description", "metadata", "type", "originSessionId"],
      merge: { algebra: "coexist", group: "claude.memory", effective_key: "identity" },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "munged_path", detector: "positional", target: "recompute from the target machine's repo path" }],
      },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${CLAUDE_HOME}/projects/{munged}/memory/{identity}",
        write_mode: "create_file",
        post_import_note: "the munged directory name is recomputed for the target machine, never inverted",
      },
      caps: { max_bytes: 1048576 },
      notes: "CLA §5.2 — the munged project-path encoding is lossy and NON-INVERTIBLE; reversing it silently corrupts memory attribution, so the rewrite recomputes from the real repo path recovered from ~/.claude.json / transcript cwd. CLA §5.3: memory is keyed to the GIT REPOSITORY root while transcripts are keyed to cwd — one directory namespace, two keying rules. Two frontmatter generations coexist (metadata.type vs top-level type, CLA §5.4); accept both, preserve on write. metadata.originSessionId is DERIVED — it points at a transcript that will not exist on the target.",
    },

    // ── settings and permissions ────────────────────────────────────────────
    {
      surface_id: "claude.settings.managed",
      kind: "setting",
      confidence: "high",
      evidence: "CLA §6.1 — managed-settings.json (+ managed-settings.d/) outranks every other layer; verified absent on the surveyed machine",
      locations: [{ scope: "managed", source_id: "claude.settings.managed.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "claude.settings.managed.file", key_path: "<key>" },
      format: "json",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "claude.settings",
        effective_key: "key_path",
        layer_order: ["claude/managed", "claude/cli", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*"],
      deep_scan_positions: [],
      argv_positions: ["apiKeyHelper", "awsCredentialExport", "statusLine.command"],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: null, write_mode: "none", post_import_note: "org-owned; never written by Continuity" },
      key_policy: {
        "MACHINE-LOCAL": [
          "voice",
          "voiceEnabled",
          "preferredNotifChannel",
          "defaultShell",
          "awsAuthRefresh",
          "awsCredentialExport",
          "apiKeyHelper",
          "statusLine.command",
          "autoMemoryDirectory",
          "cleanupPeriodDays",
        ],
        "ACCOUNT-DEPENDENT": ["model", "availableModels", "fallbackModel", "advisorModel", "fastMode", "forceLoginOrgUUID"],
        PORTABLE: [
          "permissions.*",
          "hooks",
          "enabledPlugins",
          "extraKnownMarketplaces",
          "attribution",
          "outputStyle",
          "editorMode",
          "effortLevel",
          "alwaysThinkingEnabled",
          "claudeMdExcludes",
          "skillOverrides",
          "autoMode",
        ],
        REVIEW_REQUIRED: [
          "skipDangerousModePermissionPrompt",
          "skipAutoPermissionPrompt",
          "skipWorkflowUsageWarning",
          "permissions.defaultMode",
        ],
      },
      notes: "CLA §6.1 — managed settings parse TOLERANTLY (bad entries stripped with warnings) while user/project/local settings are STRICT: one malformed key rejects the whole file and silently disables that layer. Validate before writing.",
    },
    {
      surface_id: "claude.settings.user",
      kind: "setting",
      confidence: "high",
      evidence: "CLA §6.1–6.3 — ~/.claude/settings.json (1232 B) on the surveyed machine; manifest §3.1: settings decompose to KEYS, not files",
      locations: [{ scope: "user", source_id: "claude.settings.user.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "claude.settings.user.file", key_path: "<key>" },
      format: "json",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "claude.settings",
        effective_key: "key_path",
        layer_order: ["claude/managed", "claude/cli", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*"],
      deep_scan_positions: [],
      argv_positions: ["apiKeyHelper", "awsCredentialExport", "statusLine.command"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_HOME}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/settings.json", write_mode: "merge_key" },
      key_policy: {
        "MACHINE-LOCAL": [
          "voice",
          "voiceEnabled",
          "preferredNotifChannel",
          "defaultShell",
          "awsAuthRefresh",
          "awsCredentialExport",
          "apiKeyHelper",
          "statusLine.command",
          "autoMemoryDirectory",
          "cleanupPeriodDays",
        ],
        "ACCOUNT-DEPENDENT": ["model", "availableModels", "fallbackModel", "advisorModel", "fastMode", "forceLoginOrgUUID"],
        PORTABLE: [
          "permissions.*",
          "hooks",
          "enabledPlugins",
          "extraKnownMarketplaces",
          "attribution",
          "outputStyle",
          "editorMode",
          "effortLevel",
          "alwaysThinkingEnabled",
          "claudeMdExcludes",
          "skillOverrides",
          "autoMode",
        ],
        REVIEW_REQUIRED: [
          "skipDangerousModePermissionPrompt",
          "skipAutoPermissionPrompt",
          "skipWorkflowUsageWarning",
          "permissions.defaultMode",
        ],
      },
      notes: "Authority here is KEY-DEPENDENT (adapter-architecture §2.2), not surface-wide, which is exactly what key_policy.REVIEW_REQUIRED carries: those keys SUPPRESS SAFETY PROMPTS (CLA §6.2) — importing them silently is a category of harm distinct from importing a wrong value, so those keys never ride a bulk accept. `claudeMdExcludes` merges as union_with_resolution with an empty severity order, with one absolute: the managed CLAUDE.md can never be excluded (CLA §9).",
    },
    {
      surface_id: "claude.settings.project",
      kind: "setting",
      confidence: "high",
      evidence: "CLA §6.2 — .claude/settings.json is the shared/committed layer; no such file exists in any project on the surveyed machine",
      locations: [{ scope: "project", source_id: "claude.settings.project.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "claude.settings.project.file", key_path: "<key>" },
      format: "json",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "claude.settings",
        effective_key: "key_path",
        layer_order: ["claude/managed", "claude/cli", "claude/local", "claude/project", "claude/user"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: ["env.*"],
      deep_scan_positions: [],
      argv_positions: ["apiKeyHelper", "awsCredentialExport", "statusLine.command"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${CLAUDE_PROJECT_DIR}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: {
        target: "${PROJECT}/.claude/settings.json",
        write_mode: "merge_key",
        banned_in_scopes: ["project"],
        post_import_note: "pluginConfigs is IGNORED here since v2.1.207, and permissions.allow / additionalDirectories apply only after the workspace trust dialog is accepted (CLA §3.4, §7.4) — writing them produces config the runtime will ignore",
      },
      key_policy: {
        "MACHINE-LOCAL": [
          "voice",
          "voiceEnabled",
          "preferredNotifChannel",
          "defaultShell",
          "awsAuthRefresh",
          "awsCredentialExport",
          "apiKeyHelper",
          "statusLine.command",
          "autoMemoryDirectory",
          "cleanupPeriodDays",
        ],
        "ACCOUNT-DEPENDENT": ["model", "availableModels", "fallbackModel", "advisorModel", "fastMode", "forceLoginOrgUUID"],
        PORTABLE: [
          "permissions.*",
          "hooks",
          "enabledPlugins",
          "extraKnownMarketplaces",
          "attribution",
          "outputStyle",
          "editorMode",
          "effortLevel",
          "alwaysThinkingEnabled",
          "claudeMdExcludes",
          "skillOverrides",
          "autoMode",
        ],
        REVIEW_REQUIRED: [
          "skipDangerousModePermissionPrompt",
          "skipAutoPermissionPrompt",
          "skipWorkflowUsageWarning",
          "permissions.defaultMode",
        ],
      },
      notes: "banned_in_scopes lists `project` because manifest §5.4 limits v1 imports to user scope: a project-scope write that the runtime then ignores until the trust dialog is accepted is a silently broken import, which is worse than not offering it.",
    },
    {
      surface_id: "claude.settings.local",
      kind: "setting",
      confidence: "high",
      evidence: "CLA §6.2 — ~/.claude/settings.local.json (980 B, 23 permission rules) and omega/.claude/settings.local.json (795 B, 21 rules) on the surveyed machine",
      locations: [{ scope: "local", source_id: "claude.settings.local.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "claude.settings.local.file", key_path: "<key>" },
      format: "json",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "claude.settings",
        effective_key: "key_path",
        layer_order: ["claude/managed", "claude/cli", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: ["env.*"],
      deep_scan_positions: [],
      argv_positions: ["apiKeyHelper", "awsCredentialExport", "statusLine.command"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${CLAUDE_PROJECT_DIR}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: {
        target: "${PROJECT}/.claude/settings.local.json",
        write_mode: "merge_key",
        banned_in_scopes: ["local"],
      },
      key_policy: {
        "MACHINE-LOCAL": [
          "voice",
          "voiceEnabled",
          "preferredNotifChannel",
          "defaultShell",
          "awsAuthRefresh",
          "awsCredentialExport",
          "apiKeyHelper",
          "statusLine.command",
          "autoMemoryDirectory",
          "cleanupPeriodDays",
        ],
        "ACCOUNT-DEPENDENT": ["model", "availableModels", "fallbackModel", "advisorModel", "fastMode", "forceLoginOrgUUID"],
        PORTABLE: [
          "permissions.*",
          "hooks",
          "enabledPlugins",
          "extraKnownMarketplaces",
          "attribution",
          "outputStyle",
          "editorMode",
          "effortLevel",
          "alwaysThinkingEnabled",
          "claudeMdExcludes",
          "skillOverrides",
          "autoMode",
        ],
        REVIEW_REQUIRED: [
          "skipDangerousModePermissionPrompt",
          "skipAutoPermissionPrompt",
          "skipWorkflowUsageWarning",
          "permissions.defaultMode",
        ],
      },
      notes: "CLA §7.4 — since v2.1.211 this file loads from the GIT REPOSITORY ROOT even when the session starts in a subdirectory, and 'Yes, don't ask again' resolves through worktrees to the main checkout, so all 12 omega worktrees write to one file. This is the layer that carried live provider keys inside a permission rule on the surveyed machine (CLA §10 #1).",
    },
    {
      surface_id: "claude.permissions",
      kind: "permission_rule",
      confidence: "high",
      evidence: "CLA §7; THR A1 — live GROQ/OPENAI keys found inline in a permissions.allow[] rule on the surveyed machine",
      locations: [
        { scope: "managed", source_id: "claude.settings.managed.file", key_path: "permissions.*[*]", match: "embedded" },
        { scope: "local", source_id: "claude.settings.local.file", key_path: "permissions.*[*]", match: "embedded" },
        { scope: "project", source_id: "claude.settings.project.file", key_path: "permissions.*[*]", match: "embedded" },
        { scope: "user", source_id: "claude.settings.user.file", key_path: "permissions.*[*]", match: "embedded" },
      ],
      claims: ["permissions.allow.**", "permissions.ask.**", "permissions.deny.**", "permissions.additionalDirectories.**"],
      embedded_in: { surface_id: "claude.settings.user.file", key_path: "permissions.<bucket>[i]" },
      format: "json",
      container: "embedded",
      identity: { from: "composite", template: "{0}[{1}]" },
      recognized_keys: [],
      merge: {
        algebra: "union_with_resolution",
        group: "claude.permissions",
        effective_key: "value",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
        severity_from: "capture:0",
        severity_order: ["deny", "ask", "allow"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: ["$"],
      portability: { class: "SECRET", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CLAUDE_HOME}/settings.json",
        write_mode: "merge_key",
        post_import_note: "each rule requires individual consent; wildcard-class rules and any defaultMode change are hard-blocked from bulk accept",
      },
      notes: "Severity beats layer rank: a broad Bash(aws *) deny outranks a narrow Bash(aws s3 ls) allow, so deny rules cannot carry allowlist exceptions (CLA §7.2). Two dialects coexist in one user's config — Bash(ls:*) written by the permission dialog and Bash(ls *) hand-written — normalize for comparison, preserve on write; never 'fix' Bash(git:* push), where the colon is literal and matches nothing. The space before * is load-bearing: Bash(ls *) matches `ls -la` but not `lsof`. `additionalDirectories` is matched by the same array pattern and is deliberately carried here rather than as a plain setting, because it grants file access.",
    },

    // ── v1.1 reserved kinds: declared now so a bundle never changes shape ────
    {
      surface_id: "claude.plugins.installed",
      kind: "plugin",
      confidence: "high",
      evidence: "CLA §8.2 — installed_plugins.json {version:2, plugins:{...}}; 3 installs on the surveyed machine, ~/.claude/plugins totalling 56 MB",
      locations: [{ scope: "user", source_id: "claude.plugins.installed.file", key_path: "plugins.*", match: "embedded" }],
      claims: ["plugins.**"],
      embedded_in: { surface_id: "claude.plugins.installed.file", key_path: "plugins.<id@marketplace>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["scope", "installPath", "projectPath", "version", "installedAt", "lastUpdated", "gitCommitSha"],
      merge: { algebra: "override", group: "claude.plugins", effective_key: "identity", layer_order: ["claude/user"] },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CLAUDE_HOME}" }],
      },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/plugins/installed_plugins.json", write_mode: "merge_key" },
      notes: "RESERVED for v1.1 (kinds.js RESERVED_V1_1_KINDS): declared with its real kind and location so the bundle shape is stable, but NOT populated in v1. Port the declaration, never the cache: installPath and gitCommitSha are machine-local and version-pinned, projectPath needs rewriting (CLA §8.2).",
    },
    {
      surface_id: "claude.marketplaces",
      kind: "marketplace",
      confidence: "high",
      evidence: "CLA §8.2 — known_marketplaces.json; one marketplace (anthropics/claude-plugins-official) on the surveyed machine",
      locations: [{ scope: "user", source_id: "claude.marketplaces.file", key_path: "*", match: "embedded" }],
      claims: ["*"],
      embedded_in: { surface_id: "claude.marketplaces.file", key_path: "<name>" },
      format: "json",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["source", "installLocation", "lastUpdated"],
      merge: { algebra: "override", group: "claude.marketplaces", effective_key: "identity", layer_order: ["claude/user"] },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "REWRITE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CLAUDE_HOME}/plugins/known_marketplaces.json",
        write_mode: "merge_key",
        post_import_note: "adding a marketplace is adding a code source; individual consent each, never bulk (THR T-I9)",
      },
      notes: "RESERVED for v1.1: declared, not populated in v1. authority: true — a marketplace is a code-distribution source, so it carries the same individual-consent rule as a permission rule.",
    },
    {
      surface_id: "claude.output_styles",
      kind: "output_style",
      confidence: "high",
      evidence: "CLA §6.4 — ~/.claude/output-styles/ is a documented surface, verified absent on the surveyed machine (ls)",
      locations: [{ scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/output-styles", match: "glob", glob: "*" }],
      format: "md",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: [],
      merge: { algebra: "coexist", group: "claude.output_styles", effective_key: "identity", layer_order: ["claude/user"] },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/output-styles/{identity}", write_mode: "create_file" },
      notes: "RESERVED for v1.1: declared, not populated in v1. CLA §6.4 — absence is normal, not an error; the surface exists so a machine that HAS output styles is described rather than silently missing them.",
    },
    {
      surface_id: "claude.keybindings",
      kind: "keybindings",
      confidence: "high",
      evidence: "CLA §6.4 — ~/.claude/keybindings.json is a documented surface, verified absent on the surveyed machine (ls)",
      locations: [{ scope: "user", root_id: "claude_home", path: "${CLAUDE_HOME}/keybindings.json", match: "file" }],
      format: "json",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: { algebra: "override", group: "claude.keybindings", effective_key: "identity", layer_order: ["claude/user"] },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CLAUDE_HOME}/keybindings.json", write_mode: "merge_key" },
      notes: "RESERVED for v1.1: declared, not populated in v1. Codex's nearest equivalent is [tui.keymap.{global,composer,chat}] — a different shape inside config.toml, so the cross-runtime path is UNSUPPORTED rather than convertible.",
    },
    {
      surface_id: "claude.statusline",
      kind: "statusline",
      confidence: "high",
      evidence: "CLA §6.3 — statusLine.command is classified MACHINE-LOCAL (it points at a local script); absent on the surveyed machine",
      locations: [
        { scope: "managed", source_id: "claude.settings.managed.file", key_path: "statusLine", match: "embedded" },
        { scope: "local", source_id: "claude.settings.local.file", key_path: "statusLine", match: "embedded" },
        { scope: "project", source_id: "claude.settings.project.file", key_path: "statusLine", match: "embedded" },
        { scope: "user", source_id: "claude.settings.user.file", key_path: "statusLine", match: "embedded" },
      ],
      claims: ["statusLine.**"],
      embedded_in: { surface_id: "claude.settings.user.file", key_path: "statusLine" },
      format: "json",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: ["type", "command", "padding"],
      merge: {
        algebra: "override",
        group: "claude.statusline",
        effective_key: "key_path",
        layer_order: ["claude/managed", "claude/local", "claude/project", "claude/user"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command"],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" }],
      emit: {
        target: "${CLAUDE_HOME}/settings.json",
        write_mode: "merge_key",
        disabled_form: { mode: "in_entry", key_path: "$", value: null },
        post_import_note: "runs a shell command on every render; quarantined on import like any other executable surface",
      },
      notes: "RESERVED for v1.1: declared, not populated in v1. Claude runs a shell command; Codex tui.status_line takes a list of named item IDs — no mechanical conversion exists, so the cross-runtime verdict is UNSUPPORTED (§3.2).",
    },
    {
      surface_id: "claude.launch_config",
      kind: "launch_config",
      confidence: "low",
      evidence: "CLA §8.5 — .claude/launch.json present and byte-identical in 4 repos on the surveyed machine; no public schema found, consumer and field set INFERRED from those instances",
      locations: [{ scope: "project", root_id: "project", path: "${PROJECT}/.claude/launch.json", match: "file" }],
      format: "json",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: ["version", "configurations"],
      merge: { algebra: "override", group: "claude.launch_config", effective_key: "identity", layer_order: ["claude/project"] },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: ["configurations[*].runtimeExecutable", "configurations[*].runtimeArgs"],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${PROJECT}/.claude/launch.json", write_mode: "create_file" },
      notes: "RESERVED for v1.1 (kinds.js RESERVED_V1_1_KINDS): declared with its real kind so the bundle shape is stable, but NOT populated in v1. CONFIDENCE LOW, and this is why: CLA §12.6 — no documentation for launch.json was found; the schema is INFERRED from two identical on-disk instances and the /run skill is the presumed consumer. Declared so the file is carried and described rather than dropped; recognized_keys is a best-effort guess, so most content will land in payload.unrecognized verbatim.",
    },
  ],

  capabilities: {
    instructions: "native",
    skill: "native",
    command: "native",
    mcp_server: "native",
    hook: "native",
    hook_script: "native",
    subagent: "native",
    memory: "native",
    setting: "native",
    permission_rule: "native",
    sandbox_profile: "unsupported",
    rule_script: "unsupported",
    plugin: "native",
    marketplace: "native",
    model_provider: "unsupported",
    output_style: "native",
    statusline: "native",
    keybindings: "native",
    launch_config: "native",
  },

  transforms: [
    {
      transform_id: "skill.claude-to-codex",
      kind: "skill",
      from: { runtime: "claude", surface_id: "claude.skills.user" },
      to: { runtime: "codex", surface_id: "codex.skills.agents_user" },
      operations: ["relocate"],
      fidelity: "native",
      drops: [],
      inert_on_target: [
        "context",
        "agent",
        "disable-model-invocation",
        "allowed-tools",
        "disallowed-tools",
        "model",
        "effort",
        "hooks",
        "paths",
        "background",
      ],
      state_transfer: [
        {
          from: "settings.skillOverrides.<n>",
          to: "skills.config[].enabled",
          fidelity: "lossy",
          note: "4 states (on / name-only / user-invocable-only / off) collapse to a boolean",
        },
      ],
      evidence: "COD §4.7 — both implement the agentskills.io open standard; CLA §2.2. A Claude skill directory and a Codex skill directory are, in the common case, byte-identical.",
    },
    {
      transform_id: "command.claude-to-codex",
      kind: "command",
      from: { runtime: "claude", surface_id: "claude.commands.project" },
      to: { runtime: "codex", surface_id: "codex.skills.repo" },
      operations: ["relocate", "transcode"],
      fidelity: "convert",
      drops: [],
      inert_on_target: ["allowed-tools", "disallowed-tools", "model"],
      evidence: "COD §4.6 — Codex prompts are top-level, home-dir-only and DEPRECATED, so the default target for a project-scoped Claude command is a Codex SKILL, which keeps repo scope. OpenAI's own /import maps slash commands to skills, not prompts (MANUAL:26085).",
    },
    {
      transform_id: "instructions.claude-to-codex",
      kind: "instructions",
      from: { runtime: "claude", surface_id: "claude.instructions.project" },
      to: { runtime: "codex", surface_id: "codex.instructions.project" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: [
        "@-imports (no Codex analogue — inline or flag)",
        "CLAUDE.local.md personal-project layer",
        ".claude/rules `paths` frontmatter",
        "content beyond project_doc_max_bytes (32 KiB)",
      ],
      inert_on_target: [],
      evidence: "CLA §1.3 / COD §4.1 — Codex truncates at project_doc_max_bytes with a log-only warning.",
    },
    {
      transform_id: "hook.claude-to-codex",
      kind: "hook",
      from: { runtime: "claude", surface_id: "claude.hooks.settings" },
      to: { runtime: "codex", surface_id: "codex.hooks.json" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: [
        "19 Claude-only events",
        "http and mcp_tool handler types",
        "prompt and agent handlers (parsed but skipped on target)",
        "async",
        "if",
        "once",
        "args",
        "shell",
      ],
      inert_on_target: [],
      evidence: "COD §4.8 — identical event names, matcher/handler shape and timeout semantics; imported hooks land UNTRUSTED in Codex and the user must run /hooks.",
    },
    {
      transform_id: "mcp_server.claude-to-codex",
      kind: "mcp_server",
      from: { runtime: "claude", surface_id: "claude.mcp.user" },
      to: { runtime: "codex", surface_id: "codex.mcp" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: ["headersHelper", "alwaysLoad", "ws transport (item-level UNSUPPORTED)"],
      gains: ["inline env upgraded to the name-reference env_vars form", "inline headers upgraded to env_http_headers"],
      inert_on_target: [],
      evidence: "COD §4.5 — Codex documents stdio and streamable HTTP only; SSE is undocumented in 0.144.5. The env → env_vars rewrite is a conversion that IMPROVES security.",
    },
    {
      transform_id: "subagent.claude-to-codex",
      kind: "subagent",
      from: { runtime: "claude", surface_id: "claude.subagents.user" },
      to: { runtime: "codex", surface_id: "codex.subagents" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: ["tools / disallowedTools (nearest is mcp_servers + skills.config)", "isolation", "color", "background", "permissionMode", "memory"],
      inert_on_target: [],
      evidence: "COD §4.13 — markdown body maps to developer_instructions; Codex has no per-agent tools allow-list field.",
    },
    {
      transform_id: "permission_rule.claude-to-codex",
      kind: "permission_rule",
      from: { runtime: "claude", surface_id: "claude.permissions" },
      to: { runtime: "codex", surface_id: "codex.rules" },
      operations: ["advise"],
      fidelity: "advisory",
      drops: ["tool-call globs do not map onto argv-prefix rules", "non-Bash tools have no Starlark representation"],
      inert_on_target: [],
      evidence: "COD §4.9 — 'lossy in both directions and should be treated as advisory output requiring human review, never as a silent automatic translation'.",
    },
    {
      transform_id: "memory.claude-to-codex",
      kind: "memory",
      from: { runtime: "claude", surface_id: "claude.memory.auto" },
      to: { runtime: "codex", surface_id: "codex.memories" },
      operations: ["advise"],
      fidelity: "advisory",
      drops: ["everything — Codex memories are generated state the manual says not to hand-edit"],
      inert_on_target: [],
      evidence: "COD §4.11 — 'Portability: essentially nil… generated, and secret-adjacent… These are different things wearing the same word.'",
    },
  ],

  lints: [
    {
      lint_id: "skill.frontmatter.underscore_variant",
      severity: "warn",
      applies_to: { kind: "skill", runtime: "claude" },
      predicate: { op: "has_key", in: "payload.unrecognized", key: "allowed_tools" },
      message: "frontmatter uses `allowed_tools`; only `allowed-tools` is documented, so the tool grant is almost certainly inert",
      suggested_fix: "rename the key to `allowed-tools`",
      auto_fixable: false,
      evidence: "CLA §2.3 — 160 files use the underscore form vs 117 hyphenated on the surveyed machine (union over 1,423 SKILL.md files)",
    },
    {
      lint_id: "instructions.invisible_to_runtime",
      severity: "warn",
      applies_to: { kind: "instructions", runtime: "codex" },
      predicate: {
        op: "and",
        rules: [
          { op: "not", rule: { op: "sibling_exists", kind: "instructions", runtime: "claude", name: "CLAUDE.md", scope: "same" } },
          { op: "edge_absent", rel: "imports", target_name: "AGENTS.md" },
        ],
      },
      message: "this repo has AGENTS.md but no CLAUDE.md and no @AGENTS.md import, so its instructions are invisible to Claude Code",
      suggested_fix: "add a CLAUDE.md containing `@AGENTS.md`, or symlink CLAUDE.md to AGENTS.md",
      auto_fixable: true,
      evidence: "CLA §1.4 — true of the `hipocampus` repo on the surveyed machine today: AGENTS.md only, and neither sibling CLAUDE.md imports it",
    },
    {
      lint_id: "hook.gated_by_sentinel",
      severity: "warn",
      applies_to: { kind: "hook", runtime: "claude" },
      predicate: { op: "edge_present", rel: "gated_by" },
      message: "this hook's script reads a sentinel file that exists on this machine, so the hook is currently muted; a settings-only port would silently un-mute it",
      suggested_fix: "carry the sentinel file, or state in the import summary that the hook will become active on the target",
      auto_fixable: false,
      evidence: "CLA §4.4 — notify-say.sh exits silently when ~/.claude/hooks/.quiet exists, and that sentinel exists (0 B, created 2026-07-28)",
    },
    {
      lint_id: "path.absolute_home",
      severity: "warn",
      applies_to: { kind: "*", runtime: "claude" },
      predicate: { op: "matches", in: "payload.parsed", pattern: "^/(Users|home)/" },
      message: "an absolute home path is embedded here: portable as a file, broken as behaviour on a different $HOME",
      suggested_fix: "use ${CLAUDE_PROJECT_DIR}, ${CLAUDE_SKILL_DIR} or ${CLAUDE_PLUGIN_ROOT}",
      auto_fixable: false,
      evidence: "CLA §11.4 — hook commands, MCP `command`, agent bodies, a Read() rule pointing at a deleted worktree, autoMemoryDirectory, installPath and projectPath all carry absolute paths on the surveyed machine",
    },
    {
      lint_id: "permission.dead_rule",
      severity: "warn",
      applies_to: { kind: "permission_rule", runtime: "claude" },
      predicate: { op: "references_missing_path", in: "payload.parsed" },
      message: "this permission rule references a path that does not exist; it is dead machine-specific residue",
      suggested_fix: "delete the rule",
      auto_fixable: true,
      evidence: "CLA §6.2 — omega/.claude/settings.local.json carries a Read() rule pointing at a now-deleted ephemeral agent worktree",
    },
    {
      lint_id: "mcp.url_without_type",
      severity: "warn",
      applies_to: { kind: "mcp_server", runtime: "claude" },
      predicate: {
        op: "and",
        rules: [
          { op: "has_key", in: "payload.parsed", key: "url" },
          { op: "missing_key", in: "payload.parsed", key: "type" },
        ],
      },
      message: "MCP entry has `url` but no `type`; Claude Code reads a typeless entry as stdio and skips it",
      suggested_fix: "add \"type\": \"http\" (or \"sse\" / \"ws\" as appropriate)",
      auto_fixable: true,
      evidence: "CLA §3.2 — the runtime emits `MCP server \"<name>\" has a \"url\" but no \"type\"` and the server never loads",
    },
    {
      lint_id: "secret.in_permission_rule",
      severity: "critical",
      applies_to: { kind: "permission_rule", runtime: "claude" },
      predicate: { op: "count_gt", in: "redaction_refs", value: 0 },
      message: "provider keys are stored inline in a permission rule; redacted for export, but still sitting in plaintext on this machine and they should be rotated",
      suggested_fix: "rewrite the rule to reference an environment variable rather than a literal, then rotate the key",
      auto_fixable: false,
      evidence: "THR A1 / CLA §10 #1 — a Bash() allow rule in ~/.claude/settings.local.json carries live-looking GROQ_API_KEY and OPENAI_API_KEY values; secrets in a permission rule are the one place no field-based redactor would look",
    },
    {
      lint_id: "secret.in_mcp_env",
      severity: "critical",
      applies_to: { kind: "mcp_server", runtime: "claude" },
      predicate: { op: "count_gt", in: "redaction_refs", value: 0 },
      message: "this MCP entry stores a credential inline; Claude has no name-reference form, so the value is redacted for export and the entry needs re-binding on the target",
      suggested_fix: "on a Codex target, emit env_vars / bearer_token_env_var / env_http_headers instead of the inline value",
      auto_fixable: false,
      evidence: "CLA §10 #2 — ~/.claude.json mcpServers.ElevenLabs.env.ELEVENLABS_API_KEY holds a plaintext 51-character API key on the surveyed machine",
    },
    {
      lint_id: "settings.suppresses_safety_prompt",
      severity: "warn",
      applies_to: { kind: "setting", runtime: "claude" },
      predicate: {
        op: "value_in",
        in: "origin.key_path",
        values: [
          "skipDangerousModePermissionPrompt",
          "skipAutoPermissionPrompt",
          "skipWorkflowUsageWarning",
          "permissions.defaultMode",
        ],
      },
      message: "this key suppresses a safety prompt; importing it silently is a category of harm distinct from importing a wrong value",
      suggested_fix: "review and accept it individually, never as part of a bulk settings import",
      auto_fixable: false,
      evidence: "CLA §6.2 — all three skip* keys are true at user scope on the surveyed machine; adapter-architecture §2.2 lists them as REVIEW_REQUIRED",
    },
  ],

  never_export: [
    {
      rule_id: "claude.account_identity",
      match: "${HOME}/.claude.json#oauthAccount",
      class: "auth",
      severity: "hard",
      reason: "account, org and billing metadata across 19 sub-keys; zero portability value (CLA §8.3)",
    },
    {
      rule_id: "claude.api_key_responses",
      match: "${HOME}/.claude.json#customApiKeyResponses",
      class: "auth",
      severity: "hard",
      reason: "records approved/rejected API key material (CLA §8.3)",
    },
    {
      rule_id: "claude.daemon_control_key",
      match: "${CLAUDE_HOME}/daemon/control.key",
      class: "auth",
      severity: "hard",
      reason: "local daemon control credential (CLA §10 #5)",
    },
    {
      rule_id: "claude.trust_state",
      match: "${HOME}/.claude.json#projects.*.hasTrustDialogAccepted",
      class: "trust_state",
      severity: "hard",
      reason: "a security decision tied to a specific filesystem; carrying it would silently pre-trust repositories on the new machine (CLA §7.4, §8.3)",
    },
    {
      rule_id: "claude.external_includes_approval",
      match: "${HOME}/.claude.json#projects.*.hasClaudeMdExternalIncludesApproved",
      class: "trust_state",
      severity: "hard",
      reason: "sticky per-project approval for external @-imports; transferring it pre-approves instruction sources the receiving user never saw (CLA §8.3)",
    },
    {
      rule_id: "claude.mcpjson_approvals",
      match: "${HOME}/.claude.json#projects.*.{enabledMcpjsonServers,disabledMcpjsonServers}",
      class: "trust_state",
      severity: "hard",
      reason: "pre-approving .mcp.json servers on import would defeat a deliberate supply-chain control (CLA §3.4)",
    },
    {
      rule_id: "claude.transcripts",
      match: "${CLAUDE_HOME}/projects/**/*.jsonl",
      class: "conversation_content",
      severity: "hard",
      reason: "1.2 GB of verbatim conversation and pasted content — the highest-density secret store on the machine; out of scope by design (CLA §8.4)",
    },
    {
      rule_id: "claude.history",
      match: "${CLAUDE_HOME}/history.jsonl",
      class: "conversation_content",
      severity: "hard",
      reason: "records {display, pastedContents, timestamp, project, sessionId} — raw prompt text (CLA §8.4)",
    },
    {
      rule_id: "claude.machine_identity",
      match: "${HOME}/.claude.json#{userID,machineID,anonymousId}",
      class: "machine_identity",
      severity: "hard",
      reason: "stable device and user fingerprints (CLA §10 #4)",
    },
    {
      rule_id: "claude.derived_caches",
      match: "${HOME}/.claude.json#{cachedGrowthBookFeatures,cachedStatsigGates,cachedExperimentData,clientDataCacheSlots,modelAccessCache,overageCreditGrantCache,tipsHistory,tipLifetimeShownCounts,announcementImpressions}",
      class: "derived",
      severity: "soft",
      reason: "server-refreshed caches and UI counters; reconstructable on first run and pure noise in a diff (CLA §8.3)",
    },
    {
      rule_id: "claude.file_history",
      match: "${CLAUDE_HOME}/file-history/**",
      class: "derived",
      severity: "soft",
      reason: "74 MB of /rewind checkpoints across 104 session directories (CLA §8.4)",
    },
    {
      rule_id: "claude.tasks_teams",
      match: "${CLAUDE_HOME}/{tasks,teams}/**",
      class: "derived",
      severity: "soft",
      reason: "202 task and 45 team directories of runtime state (CLA §8.4)",
    },
    {
      rule_id: "claude.session_state",
      match: "${CLAUDE_HOME}/{sessions,session-env,shell-snapshots,paste-cache,telemetry,cache,backups,plans,jobs}/**",
      class: "machine_local_runtime",
      severity: "hard",
      reason: "live session descriptors carrying pid/cwd/bridgeSessionId, plus shell snapshots and pasted content (CLA §8.4)",
    },
    {
      rule_id: "claude.ipc_locks",
      match: "${CLAUDE_HOME}/{ipc,mcp-oauth-locks,process_manager}/**",
      class: "machine_local_runtime",
      severity: "hard",
      reason: "process-local sockets, OAuth locks and process-manager state; meaningless off this machine (manifest §5.4)",
    },
    {
      rule_id: "claude.plugin_cache",
      match: "${CLAUDE_HOME}/plugins/cache/**",
      class: "derived",
      severity: "soft",
      reason: "56 MB of re-resolvable plugin payload; the declaration is portable, the cache is not (CLA §8.2)",
    },
    {
      rule_id: "claude.plugin_install_paths",
      match: "${CLAUDE_HOME}/plugins/installed_plugins.json#plugins.*.*.{installPath,gitCommitSha}",
      class: "machine_identity",
      severity: "soft",
      reason: "absolute install paths and pinned commit SHAs are machine-local; the plugin id and version are the portable part (CLA §8.2)",
    },
    {
      rule_id: "claude.worktrees",
      match: "${PROJECT}/.claude/worktrees/**",
      class: "machine_local_runtime",
      severity: "hard",
      reason: "real git worktrees nested inside .claude; ephemeral and machine-bound (CLA §8.5)",
    },
    {
      rule_id: "claude.scheduled_tasks_lock",
      match: "${PROJECT}/.claude/scheduled_tasks.lock",
      class: "machine_local_runtime",
      severity: "hard",
      reason: "holds {sessionId, pid, procStart, acquiredAt} for a running process (CLA §8.5)",
    },
    {
      rule_id: "claude.ds_store",
      match: "${CLAUDE_HOME}/**/.DS_Store",
      class: "derived",
      severity: "soft",
      reason: "macOS Finder metadata; noise in every diff (CLA §8.5)",
    },
  ],
};
