// PURE DATA. No fs, no path, no traversal, no branching on runtime name.
//
// Full transcription of adapter-architecture §2.3 (discovery) crossed with §2.4
// (semantics), amended by spike-corrections §7.2 (secret_positions split) and §7.3
// (hooks[].command is argv, not an unconditional redaction position).
//
// Constraints the data cannot express:
//  - `tokens` is expanded in declaration order. `${root:<root_id>}` resolves to that
//    root's platform-selected path; a flat token table cannot carry a per-platform
//    value, and the system config root differs on Windows (COD §6.7, still UNKNOWN).
//  - The CODEX_HOME token names the same string as the CODEX_HOME *environment
//    variable* (COD §4.10, "must already exist if set"). The engine must let the
//    environment variable win; the token cannot express its own override without
//    self-reference.
//  - [hooks.state] and [projects."<abs>"] are deliberately NOT surfaces. They appear
//    only in never_export[], so no code path can reach them (§2.4).

export default {
  id: "codex",
  display_name: "Codex",
  status: "supported",
  adapter_version: "1.0.0",

  detect: {
    present_if: [{ kind: "dir_exists", path: "${CODEX_HOME}" }],
    version: [
      { kind: "file_key", path: "${CODEX_HOME}/version.json", key_path: "version", parse: "semver_first" },
      { kind: "command", argv: ["codex", "--version"], parse: "semver_first" },
    ],
    version_required: false,
    // COD §4.3 / §5.3 — below 0.134.0 the profile mechanism is the legacy
    // [profiles.x] table form. Writing the 0.134+ shape onto an older Codex, or the
    // legacy shape onto a newer one, produces a file that parses cleanly and does
    // nothing. Refuse rather than warn (adapter-architecture §1.2, exit code 10).
    breaking_below: "0.134.0",
  },

  tokens: {
    CODEX_HOME: "${HOME}/.codex",
    CODEX_SYSTEM: "${root:codex_system}",
  },

  roots: [
    { root_id: "codex_home", scope: "user", path: "${CODEX_HOME}", declared: true },
    { root_id: "home", scope: "user", path: "${HOME}", declared: true },
    { root_id: "project", scope: "project", path: "${PROJECT}", declared: true },
    {
      root_id: "codex_system",
      scope: "system",
      platform: { darwin: "/etc/codex", linux: "/etc/codex", win32: null },
      declared: true,
    },
  ],

  // manifest §3.2 / COD §4.4 — CLI > project (closest wins) > profile > user > system
  // > built-in defaults. Six ranks including a profile layer and a system layer.
  layer_ranks: { cli: 90, project: 70, profile: 50, user: 40, system: 20 },

  project_markers: [".codex", "AGENTS.md", ".git"],

  // COD §4.4 — an untrusted project skips EVERY project `.codex/` layer, and the
  // default is untrusted. Read locally to explain the absence; never exported
  // (codex.project_trust), because carrying a trust_level launders that decision.
  project_trust: {
    source_id: "codex.config.user",
    container_key: "projects",
    key: "trust_level",
    trusted_values: ["trusted"],
    default_untrusted: true,
    evidence: "COD §4.4 — [projects.\"<abs>\"] trust_level; absent means untrusted",
  },

  // THR §3.2 Layer 2 — curated, and shown in the report so the user can see what we
  // chose NOT to redact. COD §4.5: node_repl's inline env carries path-like and
  // SHA-allowlist values that are configuration, not credentials.
  secret_key_allowlist: ["NODE_REPL_TRUSTED_CODE_PATHS"],

  sources: [
    {
      source_id: "codex.config.system.file",
      scope: "system",
      root_id: "codex_system",
      path: "${CODEX_SYSTEM}/config.toml",
      format: "toml",
      label: "/etc/codex/config.toml",
    },
    {
      source_id: "codex.config.user.file",
      scope: "user",
      root_id: "codex_home",
      path: "${CODEX_HOME}/config.toml",
      format: "toml",
      label: "~/.codex/config.toml",
    },
    {
      source_id: "codex.config.profile.file",
      scope: "profile",
      root_id: "codex_home",
      path: "${CODEX_HOME}/*.config.toml",
      format: "toml",
      label: "~/.codex/<name>.config.toml",
    },
    {
      source_id: "codex.config.project.file",
      scope: "project",
      root_id: "project",
      path: "${PROJECT}/.codex/config.toml",
      format: "toml",
      label: "${PROJECT}/.codex/config.toml",
    },
    {
      source_id: "codex.hooks.user.file",
      scope: "user",
      root_id: "codex_home",
      path: "${CODEX_HOME}/hooks.json",
      format: "json",
      label: "~/.codex/hooks.json",
    },
    {
      source_id: "codex.hooks.project.file",
      scope: "project",
      root_id: "project",
      path: "${PROJECT}/.codex/hooks.json",
      format: "json",
      label: "${PROJECT}/.codex/hooks.json",
    },
  ],

  surfaces: [
    // ── instructions ────────────────────────────────────────────────────────
    {
      surface_id: "codex.instructions.global",
      kind: "instructions",
      confidence: "high",
      evidence: "COD §4.1 / MANUAL:19619-19712 — 'Codex uses only the first non-empty file at this level'",
      locations: [
        {
          scope: "user",
          root_id: "codex_home",
          path: "${CODEX_HOME}",
          match: "file",
          order: ["AGENTS.override.md", "AGENTS.md"],
        },
      ],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: { algebra: "first_non_empty", group: "codex.instructions", effective_key: "chain", layer_order: ["codex/user"] },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      caps: { max_bytes: 32768 },
      emit: { target: "${CODEX_HOME}/AGENTS.md", write_mode: "create_file" },
      notes: "AGENTS.override.md means REPLACE, not append. Claude Code has no equivalent, so importing a Codex env that relies on an override file into Claude silently loses that semantic (COD §4.1). Emit target is AGENTS.md, never the override file, unless the user explicitly asks. project_doc_max_bytes default 32768 truncates silently (log only) — surfaced as a truncation record, never a silent drop.",
    },
    {
      surface_id: "codex.instructions.project",
      kind: "instructions",
      confidence: "high",
      evidence: "COD §4.1 / MANUAL:19619-19712 — per-directory AGENTS.override.md, then AGENTS.md, then project_doc_fallback_filenames; at most one file per directory",
      locations: [
        {
          scope: "project",
          root_id: "project",
          path: "${PROJECT}",
          match: "file",
          order: ["AGENTS.override.md", "AGENTS.md"],
          ancestor_walk: "root_to_cwd",
          at_most_one_per_dir: true,
        },
      ],
      format: "md",
      container: "file",
      identity: { from: "relpath", template: "{relpath}" },
      recognized_keys: [],
      merge: {
        algebra: "concatenate",
        group: "codex.instructions",
        effective_key: "chain",
        layer_order: ["codex/project", "codex/user"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      caps: { max_bytes: 32768 },
      emit: { target: "${PROJECT}/AGENTS.md", write_mode: "create_file" },
      notes: "Concatenated root-down, joined with blank lines; files closer to cwd override earlier guidance because they appear later in the combined prompt (COD §4.1). `order` also accepts any name in project_doc_fallback_filenames (default []), which is itself a setting — the fallback list is read from codex.config.* rather than hardcoded here. Empty files are skipped; loading stops at project_doc_max_bytes.",
    },

    // ── config layers (settings decompose to KEYS, manifest §3.1) ────────────
    {
      surface_id: "codex.config.system",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.4 / MANUAL:10680-10695 — /etc/codex/config.toml is layer 5 of the precedence chain (Unix)",
      locations: [{ scope: "system", source_id: "codex.config.system.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "codex.config.system.file", key_path: "<key>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["shell_environment_policy.set.*"],
      deep_scan_positions: [],
      argv_positions: ["notify"],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: null, write_mode: "none", post_import_note: "admin-owned layer; Continuity reads it for the effective view and never writes it" },
      notes: "COD §6.7 — the Windows equivalent of /etc/codex is UNKNOWN, which is why the root's win32 path is null rather than guessed. Above this layer on managed machines sits requirements.toml (MANUAL:10700), whose full schema was not retrieved (COD §6.6) and which is therefore not modelled.",
    },
    {
      surface_id: "codex.config.user",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.2, §4.4 — ~/.codex/config.toml; the ConfigToml struct field list is ~100 top-level keys, and the blob is near-complete but not exhaustive",
      locations: [{ scope: "user", source_id: "codex.config.user.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "<key>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["shell_environment_policy.set.*"],
      deep_scan_positions: [],
      argv_positions: ["notify"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CODEX_HOME}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      key_policy: {
        "MACHINE-LOCAL": [
          "log_dir",
          "sqlite_home",
          "js_repl_node_path",
          "js_repl_node_module_dirs",
          "model_instructions_file",
          "experimental_compact_prompt_file",
          "notify",
          "windows",
          "desktop",
        ],
        "ACCOUNT-DEPENDENT": [
          "model",
          "review_model",
          "model_context_window",
          "model_catalog_json",
          "forced_chatgpt_workspace_id",
          "forced_login_method",
          "cli_auth_credentials_store",
          "oss_provider",
        ],
        PORTABLE: [
          "approval_policy",
          "sandbox_mode",
          "sandbox_workspace_write",
          "default_permissions",
          "permissions",
          "personality",
          "model_reasoning_effort",
          "plan_mode_reasoning_effort",
          "model_reasoning_summary",
          "model_verbosity",
          "file_opener",
          "project_doc_max_bytes",
          "project_doc_fallback_filenames",
          "project_root_markers",
          "tui",
          "features",
          "agents",
          "skills",
          "memories",
          "plugins",
          "marketplaces",
        ],
        REVIEW_REQUIRED: [
          "approval_policy",
          "sandbox_mode",
          "default_permissions",
          "suppress_unstable_features_warning",
          "shell_environment_policy",
        ],
      },
      notes: "COD §4.2 — approval_policy, service_tier, web_search, skills, memories and features are documented and in active use but absent from the serde field-list blob, so a key must never be treated as invalid just because it is missing from one source: the key set is the UNION of blob and manual. COD §6.8 — orchestrator, ghost_snapshot, otel, experimental_thread_store and realtime sub-schemas are undocumented and must round-trip UNTOUCHED rather than being dropped.",
    },
    {
      surface_id: "codex.config.profile",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.3 / CLI + MANUAL:9566-9600 — '--profile no longer reads [profiles.profile-name] from config.toml'; profile files use TOP-LEVEL keys in ${CODEX_HOME}/<name>.config.toml",
      locations: [{ scope: "profile", source_id: "codex.config.profile.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "codex.config.profile.file", key_path: "<key>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["shell_environment_policy.set.*"],
      deep_scan_positions: [],
      argv_positions: ["notify"],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CODEX_HOME}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/{identity}.config.toml", write_mode: "merge_key" },
      notes: "top-level keys only; [profiles.x] tables are legacy no-ops since 0.134.0. `profile` and `profiles` remain in the struct field list as legacy no-ops, so a round-trip that writes [profiles.x] produces a file that parses cleanly and silently does nothing — a silent-data-loss class bug, which is why the adapter sets detect.breaking_below = 0.134.0 and refuses rather than warns. Profile name charset: letters, numbers, hyphens, underscores (COD §4.3).",
    },
    {
      surface_id: "codex.config.project",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.4 / MANUAL:9690ff — project .codex/config.toml, closest wins, trusted projects only; ten keys are banned here and produce a startup warning plus a silent no-op",
      locations: [{ scope: "project", source_id: "codex.config.project.file", key_path: "**", match: "embedded" }],
      embedded_in: { surface_id: "codex.config.project.file", key_path: "<key>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: ["shell_environment_policy.set.*"],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${PROJECT}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: {
        target: "${PROJECT}/.codex/config.toml",
        write_mode: "merge_key",
        banned_in_scopes: [
          "openai_base_url",
          "chatgpt_base_url",
          "apps_mcp_product_sku",
          "model_provider",
          "model_providers",
          "notify",
          "profile",
          "profiles",
          "experimental_realtime_ws_base_url",
          "otel",
        ],
        post_import_note: "an untrusted project skips ALL project .codex/ layers — config, hooks and rules — so a project-scope write can be silently inert until the user trusts the workspace",
      },
      notes: "Relative paths in a project config resolve relative to the .codex/ folder that CONTAINS it, not to cwd (COD §4.4). banned_in_scopes here lists KEY NAMES rather than scope names because the ban is per-key within this one scope; writing any of them yields a startup warning and a silent no-op, which is a security boundary (base URLs and model_providers redirect where the model traffic goes).",
    },

    // ── MCP ─────────────────────────────────────────────────────────────────
    {
      surface_id: "codex.mcp",
      kind: "mcp_server",
      confidence: "high",
      evidence: "COD §4.5 — 12 servers on the surveyed machine; [mcp_servers.node_repl.env] carries 16 inline env values",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "mcp_servers.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "mcp_servers.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "mcp_servers.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "mcp_servers.*", match: "embedded" },
      ],
      claims: ["mcp_servers.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "mcp_servers.<name>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: [
        "enabled",
        "required",
        "command",
        "args",
        "env",
        "env_vars",
        "cwd",
        "experimental_environment",
        "startup_timeout_sec",
        "tool_timeout_sec",
        "enabled_tools",
        "disabled_tools",
        "scopes",
        "oauth_resource",
        "url",
        "bearer_token_env_var",
        "http_headers",
        "env_http_headers",
      ],
      merge: {
        algebra: "override_whole_entry",
        group: "codex.mcp",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: ["env.*", "http_headers.*", "url"],
      deep_scan_positions: [],
      argv_positions: ["command", "args"],
      portability: {
        class: "SECRET",
        rewrites: [
          {
            rewrite_id: "env_to_reference",
            detector: "positional",
            target: "env_vars[] | bearer_token_env_var | env_http_headers",
          },
          { rewrite_id: "abs_path", detector: "path.absolute_home", target: "${HOME}" },
        ],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path" }],
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        disabled_form: { key_path: "enabled", value: false },
      },
      notes: "Codex has SAFE name-reference forms Claude lacks: env_vars, bearer_token_env_var, env_http_headers. Claude to Codex emit UPGRADES inline env to env_vars — a conversion that improves security. SSE is undocumented in 0.144.5; emit stdio or streamable HTTP only. Quarantine is free here: `enabled = false` is the runtime's own idiom (COD §4.5). Trust is EXECUTABLE when `command` is present, DECLARATIVE for url-only entries.",
    },

    // ── commands and skills ─────────────────────────────────────────────────
    {
      surface_id: "codex.prompts",
      kind: "command",
      confidence: "high",
      evidence: "COD §4.6 / MANUAL:19772-19834 — 'Custom prompts are deprecated. Use skills for reusable instructions.' ~/.codex/prompts is absent on the surveyed machine",
      locations: [{ scope: "user", root_id: "codex_home", path: "${CODEX_HOME}/prompts", match: "glob", glob: "*.md", depth: 1 }],
      format: "md+frontmatter",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: ["description", "argument-hint"],
      merge: { algebra: "coexist", group: "codex.commands", effective_key: "identity", layer_order: ["codex/user"] },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "INERT",
      capability: "convertible",
      emit: {
        target: null,
        write_mode: "none",
        post_import_note: "read-only legacy input: prompts are deprecated, top-level-only and not shareable via repo, so commands are emitted as Codex SKILLS instead",
      },
      caps: { max_entries: 1 },
      notes: "TOP-LEVEL Markdown files only — 'Codex scans only the top-level Markdown files in that folder'; non-Markdown ignored, subdirectories ignored, restart required to reload. Placeholders $1-$9, $ARGUMENTS, $ARGUMENTS[N], named $UPPERCASE as KEY=value, $$ for a literal $. Claude commands can be project-scoped and nested; prompts cannot, so the default conversion target is a skill (OpenAI's own /import maps slash commands to skills, MANUAL:26085).",
    },
    {
      surface_id: "codex.skills.codex_home",
      kind: "skill",
      confidence: "high",
      evidence: "COD §4.7, §6.1 — 76 skills in ~/.codex/skills on the surveyed machine and the binary contains the literal string /.codex/skills, even though the manual's table omits it",
      locations: [
        { scope: "user", root_id: "codex_home", path: "${CODEX_HOME}/skills", match: "dir_of", glob: "*/SKILL.md", depth: 2 },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: ["name", "description"],
      assets: {
        globs: ["**/*"],
        payload_policy_aware: true,
        roles: {
          "scripts/**": "script",
          "lib/**": "script",
          "bin/**": "script",
          "references/**": "reference",
          "agents/openai.yaml": "metadata",
          "*.md": "reference",
        },
      },
      merge: {
        algebra: "coexist",
        group: "codex.skills",
        effective_key: "identity",
        layer_order: ["codex/project", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${HOME}" }] },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${CODEX_HOME}/skills/{identity}/",
        write_mode: "relocate_dir",
        disabled_form: { key_path: "skills.config[].enabled", value: false },
      },
      caps: { max_bytes: 1048576 },
      notes: "Trust escalates to EXECUTABLE when a bundled script carries the exec bit (kinds.js maxTier; escalation only). COD §6.1/§6.2 — whether this directory is officially supported or legacy, and its precedence against ~/.agents/skills on a duplicate `name`, are GENUINE UNKNOWNS; `coexist` is the safe default because guessing `override` would silently hide a skill in the effective view. Duplicate `name` across scopes is documented as not merged: both appear in selectors (COD §4.7). Optional agents/openai.yaml carries UI metadata Claude ignores harmlessly.",
    },
    {
      surface_id: "codex.skills.agents_user",
      kind: "skill",
      confidence: "high",
      evidence: "COD §4.7 — the manual's discovery table lists $HOME/.agents/skills for USER scope; 12 skills there on the surveyed machine",
      locations: [
        { scope: "user", root_id: "home", path: "${HOME}/.agents/skills", match: "dir_of", glob: "*/SKILL.md", depth: 2 },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: ["name", "description"],
      assets: {
        globs: ["**/*"],
        payload_policy_aware: true,
        roles: { "scripts/**": "script", "lib/**": "script", "references/**": "reference", "agents/openai.yaml": "metadata", "*.md": "reference" },
      },
      merge: {
        algebra: "coexist",
        group: "codex.skills",
        effective_key: "identity",
        layer_order: ["codex/project", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${HOME}" }] },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${HOME}/.agents/skills/{identity}/",
        write_mode: "relocate_dir",
        disabled_form: { key_path: "skills.config[].enabled", value: false },
      },
      caps: { max_bytes: 1048576 },
      notes: "This is the DOCUMENTED user-scope location and therefore the default cross-runtime emit target for a Claude skill. Symlinked skill folders are supported and followed by the runtime; Continuity still applies the three-outcome symlink policy (THR §3.1), which is what turns '0 Codex skills' into 61 visible unresolved_link nodes on the surveyed machine.",
    },
    {
      surface_id: "codex.skills.repo",
      kind: "skill",
      confidence: "high",
      evidence: "COD §4.7 — REPO scope is $CWD/.agents/skills, each directory up to repo root, and $REPO_ROOT/.agents/skills",
      locations: [
        {
          scope: "project",
          root_id: "project",
          path: "${PROJECT}/.agents/skills",
          match: "dir_of",
          glob: "*/SKILL.md",
          depth: 2,
          ancestor_walk: "cwd_to_root",
        },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: ["name", "description"],
      assets: {
        globs: ["**/*"],
        payload_policy_aware: true,
        roles: { "scripts/**": "script", "lib/**": "script", "references/**": "reference", "agents/openai.yaml": "metadata", "*.md": "reference" },
      },
      merge: {
        algebra: "coexist",
        group: "codex.skills",
        effective_key: "identity",
        layer_order: ["codex/project", "codex/user", "codex/system"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [{ rewrite_id: "abs_project", detector: "path.absolute_home", target: "${PROJECT}" }] },
      trust_tier: "INERT",
      capability: "native",
      emit: {
        target: "${PROJECT}/.agents/skills/{identity}/",
        write_mode: "relocate_dir",
        disabled_form: { key_path: "skills.config[].enabled", value: false },
      },
      caps: { max_bytes: 1048576 },
      notes: "The one skill scope Claude cannot express at repo level without .claude/skills; this is the target that makes a project-scoped Claude COMMAND portable (COD §4.6). ancestor_walk is cwd_to_root because the manual walks up from $CWD to the repo root, the opposite direction from the instruction chain.",
    },
    {
      surface_id: "codex.skills.admin",
      kind: "skill",
      confidence: "high",
      evidence: "COD §4.7 — ADMIN scope is /etc/codex/skills in the manual's discovery table",
      locations: [
        { scope: "system", root_id: "codex_system", path: "${CODEX_SYSTEM}/skills", match: "dir_of", glob: "*/SKILL.md", depth: 2 },
      ],
      format: "md+frontmatter",
      container: "directory",
      identity: { from: "dirname", template: "{dirname}" },
      recognized_keys: ["name", "description"],
      assets: { globs: ["**/*"], payload_policy_aware: true, roles: { "scripts/**": "script", "*.md": "reference" } },
      merge: {
        algebra: "coexist",
        group: "codex.skills",
        effective_key: "identity",
        layer_order: ["codex/project", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "INERT",
      capability: "native",
      emit: { target: null, write_mode: "none", post_import_note: "admin-owned; Continuity reads it for the effective view and never writes it" },
      notes: "Admin-installed skills are org-owned like Claude's managed layer: described so the effective view is complete, never emitted. COD §6.7 — the Windows equivalent of /etc/codex/skills is UNKNOWN.",
    },
    {
      surface_id: "codex.skills_config",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.2, §4.7 — [[skills.config]] path + enabled is the documented disable-without-deleting mechanism",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "skills.config[*]", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "skills.config[*]", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "skills.config[*]", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "skills.config[*]", match: "embedded" },
      ],
      claims: ["skills.config.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "skills.config[i]" },
      format: "toml",
      container: "embedded",
      identity: { from: "field", field: "path", template: "{field}" },
      recognized_keys: ["path", "enabled"],
      merge: {
        algebra: "override",
        group: "codex.skills_config",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_skill_path", detector: "path.absolute_home", target: "${CODEX_HOME}/skills" }],
      },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "`path` is an ABSOLUTE path to a SKILL.md, so identity is machine-bound and must be rewritten on import (COD §5.9). This is the target of the skill enablement `enabled_by` edge: a port that copies skills without their enablement state changes behaviour (manifest §1.6). Claude's skillOverrides has four states against this boolean — the state transfer is lossy by construction.",
    },

    // ── hooks ───────────────────────────────────────────────────────────────
    {
      surface_id: "codex.hooks.json",
      kind: "hook",
      confidence: "high",
      evidence: "COD §4.8 / MANUAL:20243-20460 — ~/.codex/hooks.json and <project>/.codex/hooks.json, event to matcher-group to handlers",
      locations: [
        { scope: "user", source_id: "codex.hooks.user.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "project", source_id: "codex.hooks.project.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
      ],
      claims: ["hooks.**"],
      embedded_in: { surface_id: "codex.hooks.user.file", key_path: "hooks.<Event>[i].hooks[j]" },
      format: "json",
      container: "embedded",
      identity: { from: "composite", template: "{0}.{1}.{2}" },
      recognized_keys: ["type", "command", "timeout", "statusMessage", "additionalContextLimit", "commandWindows", "command_windows"],
      merge: {
        algebra: "aggregate",
        group: "codex.hooks",
        effective_key: "capture:0",
        layer_order: ["codex/project", "codex/user", "codex/system"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command", "commandWindows", "command_windows"],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CODEX_HOME}" }],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [
        { rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" },
        { rel: "gated_by", from: "body", detector: "existing_dotfile_path" },
      ],
      emit: {
        target: "${CODEX_HOME}/hooks.json",
        write_mode: "merge_key",
        disabled_form: { key_path: "enabled", value: false },
        post_import_note: "imported hooks land UNTRUSTED; the user must run /hooks in the TUI. Say so rather than let the import look silently broken (COD §4.8)",
      },
      notes: "Higher-precedence layers do NOT replace lower-precedence hooks — all matching hooks from all layers run, concurrently (MANUAL:20275). timeout is in SECONDS, default 600, SessionEnd defaults to 1s with a 3s max. Only type: command runs today; `prompt` and `agent` are parsed but skipped, and `async` is parsed but unsupported. Trust is recorded against the hook's HASH, so any edit re-arms review — which is why [hooks.state] is never exported.",
    },
    {
      surface_id: "codex.hooks.inline",
      kind: "hook",
      confidence: "high",
      evidence: "COD §4.8 — inline [[hooks.PreToolUse]] + [[hooks.PreToolUse.hooks]] arrays-of-tables in config.toml are the TOML equivalent of the JSON shape",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "hooks.*[*].hooks[*]", match: "embedded" },
      ],
      claims: ["hooks.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "hooks.<Event>[i].hooks[j]" },
      format: "toml",
      container: "embedded",
      identity: { from: "composite", template: "{0}.{1}.{2}" },
      recognized_keys: ["type", "command", "timeout", "statusMessage", "additionalContextLimit", "commandWindows", "command_windows"],
      merge: {
        algebra: "aggregate",
        group: "codex.hooks",
        effective_key: "capture:0",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["command", "commandWindows", "command_windows"],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${CODEX_HOME}" }],
      },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" }],
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        disabled_form: { key_path: "enabled", value: false },
        post_import_note: "imported hooks land UNTRUSTED; the user must run /hooks (COD §4.8)",
      },
      notes: "The TOML shape is why a line-based scanner is not enough: arrays-of-tables and inline tables both appear here (adapter-architecture §1.4). Hook definitions use CamelCase event names while [hooks.state] keys use snake_case for the same events — two naming conventions in one file (COD §4.8).",
    },

    // ── subagents ───────────────────────────────────────────────────────────
    {
      surface_id: "codex.subagents",
      kind: "subagent",
      confidence: "high",
      evidence: "COD §4.13 / MANUAL:1888-1990 — .codex/agents/<n>.toml with `name` as the source of truth, not the filename; plus [agents.<n>] config_file references",
      locations: [
        { scope: "project", root_id: "project", path: "${PROJECT}/.codex/agents", match: "glob", glob: "*.toml" },
        { scope: "user", root_id: "codex_home", path: "${CODEX_HOME}/agents", match: "glob", glob: "*.toml" },
      ],
      format: "toml",
      container: "file",
      identity: { from: "field", field: "name", template: "{field}" },
      recognized_keys: ["name", "description", "developer_instructions", "model", "model_reasoning_effort", "sandbox_mode", "config_file"],
      merge: {
        algebra: "override",
        group: "codex.subagents",
        effective_key: "identity",
        layer_order: ["codex/project", "codex/user"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "REWRITE", rewrites: [{ rewrite_id: "abs_home", detector: "path.absolute_home", target: "${HOME}" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "body", detector: "existing_dotfile_path" }],
      emit: { target: "${CODEX_HOME}/agents/{identity}.toml", write_mode: "create_file" },
      notes: "A custom agent whose `name` matches a built-in (e.g. explorer) TAKES PRECEDENCE, so identity collisions are semantically meaningful rather than an error. Any other config.toml key is allowed in these files because Codex loads them as configuration layers for spawned sessions — so recognized_keys is deliberately the documented core and everything else round-trips in payload.unrecognized. Also referenceable via [agents.<n>] config_file, relative to the defining config.toml. The manual itself concedes the format may evolve.",
    },

    // ── approval, sandbox, rules ────────────────────────────────────────────
    {
      surface_id: "codex.approval",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.9 — approval_policy is a STRING (untrusted | on-request | never) OR a TABLE ({granular = {...}}, MANUAL:11156-11186); on-failure is parse-only legacy in 0.144.5",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "approval_policy", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "approval_policy", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "approval_policy", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "approval_policy", match: "embedded" },
      ],
      claims: ["approval_policy.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "approval_policy" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: ["granular"],
      merge: {
        algebra: "override",
        group: "codex.approval",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "advisory",
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        post_import_note: "changes when Codex asks before acting; individual consent, never bulk",
      },
      notes: "STRING-OR-TABLE is a schema trap for any naive validator, which is why the schema layer models union types by hand rather than assuming JSON-Schema `type` (adapter-architecture §1.4). `on-failure` is legacy-accept, never-emit. On managed machines requirements.toml can forbid values such as approval_policy = never (MANUAL:10700). Claude's nearest analogue is permissions.defaultMode, and the mapping is advisory only.",
    },
    {
      surface_id: "codex.sandbox",
      kind: "sandbox_profile",
      confidence: "high",
      evidence: "COD §4.9 — sandbox_mode (read-only | workspace-write | danger-full-access), [sandbox_workspace_write] (MANUAL:11392-11408) and default_permissions",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "sandbox_mode", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "sandbox_mode", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "sandbox_mode", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "sandbox_mode", match: "embedded" },
        { scope: "system", source_id: "codex.config.system.file", key_path: "sandbox_workspace_write", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "sandbox_workspace_write", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "sandbox_workspace_write", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "sandbox_workspace_write", match: "embedded" },
        { scope: "system", source_id: "codex.config.system.file", key_path: "default_permissions", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "default_permissions", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "default_permissions", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "default_permissions", match: "embedded" },
      ],
      claims: ["sandbox_mode.**", "sandbox_workspace_write.**", "default_permissions.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "sandbox_workspace_write" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: ["writable_roots", "network_access", "exclude_tmpdir_env_var", "exclude_slash_tmp"],
      merge: {
        algebra: "override",
        group: "codex.sandbox",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["network.proxy_url", "network.socks_url"],
      deep_scan_positions: [],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "writable_roots", detector: "path.absolute_home", target: "${PROJECT}" }],
      },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        post_import_note: "grants filesystem and network authority; individual consent, never bulk",
      },
      notes: "writable_roots are ABSOLUTE paths (default []) and network_access defaults to false. By default .git/ and .codex/ inside a workspace root stay read-only while the rest is writable (MANUAL:8531). Claude Code has no analogue at all, so the cross-runtime verdict is UNSUPPORTED rather than advisory — there is nothing to advise toward.",
    },
    {
      surface_id: "codex.permission_profiles",
      kind: "sandbox_profile",
      confidence: "high",
      evidence: "COD §4.9 / MANUAL:11204, 11472-11541 — named [permissions.<name>] profiles with workspace_roots, filesystem, network and unix_sockets sub-tables; built-ins :read-only, :workspace, :danger-full-access",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "permissions.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "permissions.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "permissions.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "permissions.*", match: "embedded" },
      ],
      claims: ["permissions.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "permissions.<name>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["workspace_roots", "filesystem", "network", "glob_scan_max_depth"],
      merge: {
        algebra: "override",
        group: "codex.permission_profiles",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["network.proxy_url", "network.socks_url", "network.admin_url"],
      deep_scan_positions: [],
      argv_positions: [],
      portability: {
        class: "REWRITE",
        rewrites: [{ rewrite_id: "workspace_roots", detector: "path.absolute_home", target: "${PROJECT}" }],
      },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        post_import_note: "a named profile can grant network egress and filesystem writes; individual consent, never bulk",
      },
      notes: "Codex-only, no Claude analogue: network.domains distinguishes `*.` (subdomains) from `**.` (apex plus subdomains), and four dangerously_allow_* escapes exist. proxy_url / socks_url / admin_url are secret positions because a proxy URL can carry userinfo credentials.",
    },
    {
      surface_id: "codex.rules",
      kind: "rule_script",
      confidence: "high",
      evidence: "COD §4.9, §5.1 — default.rules on the surveyed machine contains a live API key in a curl -H argv, recorded from a TUI allow-list action",
      locations: [
        { scope: "user", root_id: "codex_home", path: "${CODEX_HOME}/rules", match: "glob", glob: "*.rules" },
        { scope: "system", root_id: "codex_system", path: "${CODEX_SYSTEM}/rules", match: "glob", glob: "*.rules" },
        { scope: "project", root_id: "project", path: "${PROJECT}/.codex/rules", match: "glob", glob: "*.rules" },
      ],
      format: "starlark",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: ["prefix_rule"],
      merge: {
        algebra: "union_with_resolution",
        group: "codex.rules",
        effective_key: "value",
        layer_order: ["codex/project", "codex/user", "codex/system"],
        severity_order: ["forbidden", "prompt", "allow"],
        suppressed_when: "project_untrusted",
      },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: ["$"],
      portability: { class: "SECRET", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: { target: null, write_mode: "none" },
      never_export: {
        severity: "hard",
        reason: "records the full argv of every command the user allow-listed in the TUI; a general-purpose secret sink",
      },
      notes: "SCAN-AND-REFUSE, not scan-and-warn. Structure is reported (rule count, decisions, which commands are allow-listed by name) so the user learns what exists; the BYTES NEVER LEAVE. Emit is `none` in both directions: Claude has no Starlark evaluator. Single function prefix_rule(pattern, decision, justification, match, not_match) with decision in allow (default) | prompt | forbidden, most restrictive wins. Compound `bash -lc` scripts are tree-sitter split into individual commands only when the script is a linear chain of plain words joined by && || ; | — anything with redirection, substitution, variables, globs or control flow is one opaque invocation.",
    },

    // ── shell environment ───────────────────────────────────────────────────
    {
      surface_id: "codex.shell_env_policy",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.2 — [shell_environment_policy] inherit/exclude/set/include_only; `set` is an explicit map that ALWAYS WINS and is the documented place an inline secret lands",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "shell_environment_policy", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "shell_environment_policy", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "shell_environment_policy", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "shell_environment_policy", match: "embedded" },
      ],
      claims: ["shell_environment_policy.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "shell_environment_policy" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: ["inherit", "ignore_default_excludes", "exclude", "set", "include_only", "use_profile"],
      merge: {
        algebra: "override",
        group: "codex.shell_env_policy",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: ["set.*"],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "SECRET", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "convertible",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "The default excludes strip variable names containing KEY, SECRET or TOKEN (case-insensitive) unless ignore_default_excludes is true — so a config that sets ignore_default_excludes = true has deliberately widened the blast radius and should be surfaced. Claude's nearest analogue is settings.env, hence convertible rather than native.",
    },

    // ── memories ────────────────────────────────────────────────────────────
    {
      surface_id: "codex.memories",
      kind: "memory",
      confidence: "high",
      evidence: "COD §4.11 / MANUAL:22167-22275 — 118 generated files under ~/.codex/memories on the surveyed machine, and the directory is itself a git repository",
      locations: [{ scope: "user", root_id: "codex_home", path: "${CODEX_HOME}/memories", match: "glob", glob: "*.md" }],
      format: "md",
      container: "file",
      identity: { from: "basename", template: "{basename}" },
      recognized_keys: [],
      merge: { algebra: "coexist", group: "codex.memories", effective_key: "identity", layer_order: ["codex/user"] },
      secret_positions: [],
      deep_scan_positions: ["$"],
      argv_positions: [],
      portability: { class: "DERIVED", rewrites: [] },
      trust_tier: "INERT",
      capability: "advisory",
      emit: {
        target: null,
        write_mode: "none",
        post_import_note: "at most, offer to carry a hand-written MEMORY.md-style index across after human review",
      },
      notes: "DERIVED, and the manual says so plainly: 'Treat these files as generated state… don't rely on editing them by hand' and 'Don't store secrets in memories… review memory files before sharing your Codex home directory.' Content is machine-specific (absolute sessions/**/rollout-*.jsonl paths, thread UUIDs, branch names). Claude memories are HAND-AUTHORED markdown; these are machine-generated summaries — different things wearing the same word (COD §4.11).",
    },

    // ── v1.1 reserved kinds: declared now so a bundle never changes shape ────
    {
      surface_id: "codex.model_providers",
      kind: "model_provider",
      confidence: "high",
      evidence: "COD §4.15 / MANUAL:11852-11956 — [model_providers.<id>] with env_key, http_headers, env_http_headers, experimental_bearer_token and an [.auth] command block",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "model_providers.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "model_providers.*", match: "embedded" },
      ],
      claims: ["model_providers.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "model_providers.<id>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: [
        "name",
        "base_url",
        "wire_api",
        "env_key",
        "env_key_instructions",
        "query_params",
        "http_headers",
        "env_http_headers",
        "request_max_retries",
        "stream_max_retries",
        "stream_idle_timeout_ms",
        "supports_websockets",
        "requires_openai_auth",
        "experimental_bearer_token",
        "auth",
      ],
      merge: {
        algebra: "override",
        group: "codex.model_providers",
        effective_key: "identity",
        layer_order: ["codex/user", "codex/system"],
      },
      secret_positions: ["http_headers.*", "experimental_bearer_token"],
      deep_scan_positions: [],
      argv_positions: ["auth.command", "auth.args"],
      portability: { class: "SECRET", rewrites: [{ rewrite_id: "env_key_reference", detector: "positional", target: "env_key" }] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "RESERVED for v1.1 (kinds.js RESERVED_V1_1_KINDS): declared with its real kind and location so the bundle shape is stable, but NOT populated in v1. USER AND SYSTEM SCOPE ONLY — model_providers is on the project-config banned-key list, and writing it there is a silent no-op that also redirects where model traffic goes. `wire_api` accepts only `responses`; experimental_bearer_token is a dev-only inline secret; reserved ids are openai, ollama, lmstudio, amazon-bedrock. The provider key VALUE never belongs in config: env_key names the variable.",
    },
    {
      surface_id: "codex.plugins",
      kind: "plugin",
      confidence: "high",
      evidence: "COD §4.14 / MANUAL:23560 — [plugins.\"<id>@<marketplace>\"] enabled = <bool>; 12 plugins across 4 marketplaces on the surveyed machine",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "plugins.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "plugins.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "plugins.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "plugins.*", match: "embedded" },
      ],
      claims: ["plugins.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "plugins.<id@marketplace>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["enabled"],
      merge: {
        algebra: "override",
        group: "codex.plugins",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "RESERVED for v1.1: declared, not populated in v1. Port the DECLARATION, never the cache under ~/.codex/plugins/cache — the declaration is small, secret-free and re-resolvable. A plugin id is not portable across ecosystems (openai-* vs anthropics/claude-plugins-official), so the cross-runtime verdict is UNSUPPORTED.",
    },
    {
      surface_id: "codex.marketplaces",
      kind: "marketplace",
      confidence: "high",
      evidence: "COD §4.14 — [marketplaces.<name>] source_type, source, last_updated, last_revision; 4 marketplaces on the surveyed machine",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "marketplaces.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "marketplaces.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "marketplaces.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "marketplaces.*", match: "embedded" },
      ],
      claims: ["marketplaces.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "marketplaces.<name>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: ["source_type", "source", "last_updated", "last_revision"],
      merge: {
        algebra: "override",
        group: "codex.marketplaces",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        post_import_note: "adding a marketplace is adding a code source; individual consent each, never bulk (THR T-I9)",
      },
      notes: "RESERVED for v1.1: declared, not populated in v1. last_updated and last_revision are DERIVED cache bookkeeping; source_type + source are the portable pair. authority: true because a marketplace is a code-distribution source.",
    },
    {
      surface_id: "codex.tui",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.2 — [tui] notifications, notification_method, animations, alternate_screen, resume_cwd, status_line, terminal_title, theme, [tui.keymap.*]",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "tui.**", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "tui.**", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "tui.**", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "tui.**", match: "embedded" },
      ],
      claims: ["tui.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "tui.<key>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [
        "notifications",
        "notification_method",
        "notification_condition",
        "animations",
        "alternate_screen",
        "resume_cwd",
        "status_line",
        "terminal_title",
        "theme",
        "keymap",
        "model_availability_nux",
      ],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "RESERVED for v1.1: declared, not populated in v1. Carries BOTH of Claude's separate v1.1 surfaces — tui.status_line is Claude's statusline (a list of named item IDs vs a shell command) and tui.keymap is Claude's keybindings.json — which is why both cross-runtime verdicts are UNSUPPORTED rather than convertible.",
    },
    {
      surface_id: "codex.notify",
      kind: "statusline",
      confidence: "high",
      evidence: "COD §4.15 / MANUAL:11146 — `notify` is an argv array, e.g. [\"notify-send\", \"Codex\"], disabled when unset, and BANNED in project config",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "notify", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "notify", match: "embedded" },
      ],
      claims: ["notify.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "notify" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.notify",
        effective_key: "key_path",
        layer_order: ["codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: ["$"],
      portability: { class: "MACHINE-LOCAL", rewrites: [] },
      trust_tier: "EXECUTABLE",
      capability: "native",
      derive_edges: [{ rel: "references_path", from: "argv0", detector: "existing_dotfile_path", target_kind: "hook_script" }],
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        disabled_form: { key_path: "notify", value: null },
        post_import_note: "spawns a local program on every notification; quarantined on import like any other executable surface",
      },
      notes: "RESERVED for v1.1: declared, not populated in v1. USER AND SYSTEM SCOPE ONLY — `notify` is on the project-config banned-key list (COD §4.4), so a project-scope write is a silent no-op. The whole value is an argv array, hence argv_positions: [\"$\"].",
    },
    {
      surface_id: "codex.features",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.15 — [features] table; 93 flags on the 0.144.5 build with stages stable | experimental | under development | deprecated | removed",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "features.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "features.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "features.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "features.*", match: "embedded" },
      ],
      claims: ["features.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "features.<flag>" },
      format: "toml",
      container: "embedded",
      identity: { from: "key_path", template: "{key_path}" },
      recognized_keys: [],
      merge: {
        algebra: "override",
        group: "codex.settings",
        effective_key: "key_path",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      capability: "native",
      emit: { target: "${CODEX_HOME}/config.toml", write_mode: "merge_key" },
      notes: "RESERVED for v1.1: declared, not populated in v1. Portable but VERSION-COUPLED — a flag valid on 0.144.5 may be `removed` on the target build (COD §5.10), which is why the manifest records the source version and the import warns on a large version gap. features.hooks defaults to true (stable); features.memories defaults to false.",
    },
    {
      surface_id: "codex.apps",
      kind: "setting",
      confidence: "high",
      evidence: "COD §4.15 / MANUAL:11960-12002 — [apps._default] and [apps.<name>] with enabled, destructive_enabled, open_world_enabled, approvals_reviewer, default_tools_approval_mode and per-tool sub-tables",
      locations: [
        { scope: "system", source_id: "codex.config.system.file", key_path: "apps.*", match: "embedded" },
        { scope: "user", source_id: "codex.config.user.file", key_path: "apps.*", match: "embedded" },
        { scope: "profile", source_id: "codex.config.profile.file", key_path: "apps.*", match: "embedded" },
        { scope: "project", source_id: "codex.config.project.file", key_path: "apps.*", match: "embedded" },
      ],
      claims: ["apps.**"],
      embedded_in: { surface_id: "codex.config.user.file", key_path: "apps.<name>" },
      format: "toml",
      container: "embedded",
      identity: { from: "map_key", template: "{0}" },
      recognized_keys: [
        "enabled",
        "destructive_enabled",
        "open_world_enabled",
        "approvals_reviewer",
        "default_tools_approval_mode",
        "tools",
      ],
      merge: {
        algebra: "override",
        group: "codex.apps",
        effective_key: "identity",
        layer_order: ["codex/cli", "codex/project", "codex/profile", "codex/user", "codex/system"],
      },
      secret_positions: [],
      deep_scan_positions: [],
      argv_positions: [],
      portability: { class: "PORTABLE", rewrites: [] },
      trust_tier: "DECLARATIVE",
      authority: true,
      capability: "native",
      emit: {
        target: "${CODEX_HOME}/config.toml",
        write_mode: "merge_key",
        post_import_note: "destructive_enabled and open_world_enabled widen what a connector may do; individual consent",
      },
      notes: "RESERVED for v1.1: declared, not populated in v1. authority: true because destructive_enabled / open_world_enabled / default_tools_approval_mode change what a connector is allowed to do without asking. Claude Code has no connector-permission table, so the cross-runtime verdict is UNSUPPORTED.",
    },
  ],

  capabilities: {
    instructions: "native",
    skill: "native",
    command: "convertible",
    mcp_server: "native",
    hook: "native",
    hook_script: "native",
    subagent: "native",
    memory: "advisory",
    setting: "native",
    permission_rule: "advisory",
    sandbox_profile: "native",
    rule_script: "native",
    plugin: "native",
    marketplace: "native",
    model_provider: "native",
    output_style: "unsupported",
    statusline: "native",
    keybindings: "native",
    launch_config: "unsupported",
  },

  transforms: [
    {
      transform_id: "skill.codex-to-claude",
      kind: "skill",
      from: { runtime: "codex", surface_id: "codex.skills.agents_user" },
      to: { runtime: "claude", surface_id: "claude.skills.user" },
      operations: ["relocate"],
      fidelity: "native",
      drops: [],
      inert_on_target: ["agents/openai.yaml"],
      state_transfer: [
        {
          from: "skills.config[].enabled",
          to: "settings.skillOverrides.<n>",
          fidelity: "lossy",
          note: "boolean widens to 4 states; `false` maps to `off` and `true` to `on`",
        },
      ],
      evidence: "COD §4.7 — 'a Claude Code skill directory and a Codex skill directory are, in the common case, byte-identical'; the differences are the host directory, the invocation sigil and Codex-only agents/openai.yaml",
    },
    {
      transform_id: "instructions.codex-to-claude",
      kind: "instructions",
      from: { runtime: "codex", surface_id: "codex.instructions.project" },
      to: { runtime: "claude", surface_id: "claude.instructions.project" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: [
        "AGENTS.override.md replace-semantics has no Claude equivalent",
        "project_doc_fallback_filenames",
        "at_most_one_per_dir selection",
      ],
      inert_on_target: [],
      evidence: "COD §4.1 hazard note, verbatim — importing a Codex env that relies on an override file into Claude silently loses the 'replace, don't append' semantics",
    },
    {
      transform_id: "command.codex-to-claude",
      kind: "command",
      from: { runtime: "codex", surface_id: "codex.prompts" },
      to: { runtime: "claude", surface_id: "claude.commands.user" },
      operations: ["relocate"],
      fidelity: "convert",
      drops: [],
      inert_on_target: ["argument-hint"],
      evidence: "COD §4.6 — near-lossless: $ARGUMENTS is spelled identically on both sides, and Claude adds project scope and nesting the source never had",
    },
    {
      transform_id: "hook.codex-to-claude",
      kind: "hook",
      from: { runtime: "codex", surface_id: "codex.hooks.json" },
      to: { runtime: "claude", surface_id: "claude.hooks.settings" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: ["statusMessage", "additionalContextLimit", "commandWindows"],
      inert_on_target: [],
      evidence: "COD §4.8 — identical event names, matcher/handler shape and timeout semantics; the three dropped fields have no Claude representation",
    },
    {
      transform_id: "mcp_server.codex-to-claude",
      kind: "mcp_server",
      from: { runtime: "codex", surface_id: "codex.mcp" },
      to: { runtime: "claude", surface_id: "claude.mcp.user" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: [
        "enabled",
        "required",
        "startup_timeout_sec",
        "tool_timeout_sec",
        "enabled_tools",
        "disabled_tools",
        "scopes",
        "oauth_resource",
        "cwd",
        "experimental_environment",
      ],
      inert_on_target: [],
      evidence: "COD §4.5 — ten Codex-only fields with no Claude representation, which is why the kind is CONVERT and not NATIVE; X to C loses real configuration (timeouts, tool allow/deny lists, OAuth scopes)",
    },
    {
      transform_id: "subagent.codex-to-claude",
      kind: "subagent",
      from: { runtime: "codex", surface_id: "codex.subagents" },
      to: { runtime: "claude", surface_id: "claude.subagents.user" },
      operations: ["transcode"],
      fidelity: "convert",
      drops: ["arbitrary session-config keys (mcp_servers, skills.config, … inside the agent file)"],
      inert_on_target: [],
      evidence: "COD §4.13 — developer_instructions maps to the Claude markdown body; Codex agent files can carry arbitrary session config Claude cannot express",
    },
    {
      transform_id: "rule_script.codex-to-claude",
      kind: "rule_script",
      from: { runtime: "codex", surface_id: "codex.rules" },
      to: { runtime: "claude", surface_id: "claude.permissions" },
      operations: ["advise"],
      fidelity: "advisory",
      drops: ["everything — the bytes never leave the machine; only rule count and decisions are reported"],
      inert_on_target: [],
      evidence: "COD §4.9, §5.1 — no Starlark evaluator exists in Claude, and the file is a never-export secret sink, so the only legitimate output is an advisory summary",
    },
    {
      transform_id: "memory.codex-to-claude",
      kind: "memory",
      from: { runtime: "codex", surface_id: "codex.memories" },
      to: { runtime: "claude", surface_id: "claude.memory.auto" },
      operations: ["advise"],
      fidelity: "advisory",
      drops: ["absolute rollout paths", "thread UUIDs", "supporting-evidence blocks"],
      inert_on_target: [],
      evidence: "COD §4.11 — 'Portability: essentially nil'; at most a hand-written MEMORY.md-style index moves across after human review",
    },
  ],

  lints: [
    {
      lint_id: "mcp.inline_env_secret",
      severity: "warn",
      applies_to: { kind: "mcp_server", runtime: "codex" },
      predicate: {
        op: "and",
        rules: [
          { op: "has_key", in: "payload.parsed", key: "env" },
          { op: "missing_key", in: "payload.parsed", key: "env_vars" },
        ],
      },
      message: "this MCP entry stores values inline in `env` when the safe name-reference form `env_vars` exists; inline values are copied as-is and are the most common way a token ends up in a shareable file",
      suggested_fix: "move the value to the parent environment and list its NAME in env_vars (or bearer_token_env_var / env_http_headers for the HTTP transport)",
      auto_fixable: true,
      evidence: "COD §4.5, §5.8 — [mcp_servers.node_repl.env] carries 16 inline env values on the surveyed machine",
    },
    {
      lint_id: "codex.rules.secret_sink",
      severity: "critical",
      applies_to: { kind: "rule_script", runtime: "codex" },
      predicate: { op: "count_gt", in: "redaction_refs", value: 0 },
      message: "credential material was found inside a .rules file; the file is refused for export and the key should be rotated",
      suggested_fix: "rotate the credential and remove the prefix_rule that recorded it",
      auto_fixable: false,
      evidence: "COD §5.1 — default.rules on the FIRST machine examined contains a live API key inside a curl -H argument, recorded automatically by a TUI allow-list action",
    },
    {
      lint_id: "codex.profile.legacy_table",
      severity: "critical",
      applies_to: { kind: "setting", runtime: "codex" },
      predicate: {
        op: "or",
        rules: [
          { op: "matches", in: "origin.key_path", pattern: "^profiles\\." },
          { op: "value_in", in: "origin.key_path", values: ["profile"] },
        ],
      },
      message: "[profiles.x] tables and the top-level `profile` selector are legacy no-ops since 0.134.0; this config parses cleanly and does nothing",
      suggested_fix: "move the settings into ${CODEX_HOME}/<name>.config.toml as TOP-LEVEL keys and delete the table and selector",
      auto_fixable: false,
      evidence: "COD §4.3 / MANUAL:9566-9600 — '--profile no longer reads [profiles.profile-name] from config.toml, and the top-level profile selector is no longer supported'; this is a silent-data-loss class bug",
    },
    {
      lint_id: "codex.config.project.banned_key",
      severity: "warn",
      applies_to: { kind: "setting", runtime: "codex" },
      predicate: {
        op: "and",
        rules: [
          { op: "value_in", in: "scope", values: ["project"] },
          {
            op: "value_in",
            in: "origin.key_path",
            values: [
              "openai_base_url",
              "chatgpt_base_url",
              "apps_mcp_product_sku",
              "model_provider",
              "model_providers",
              "notify",
              "profile",
              "profiles",
              "experimental_realtime_ws_base_url",
              "otel",
            ],
          },
        ],
      },
      message: "this key is banned in project-local config: Codex ignores it and prints a startup warning, so the setting silently does nothing",
      suggested_fix: "move it to ${CODEX_HOME}/config.toml (user scope)",
      auto_fixable: false,
      evidence: "COD §4.4 / MANUAL:9690ff — the banned list is a security boundary: base URLs and model_providers redirect where model traffic goes",
    },
    {
      lint_id: "path.absolute_home",
      severity: "warn",
      applies_to: { kind: "*", runtime: "codex" },
      predicate: { op: "matches", in: "payload.parsed", pattern: "^/(Users|home)/" },
      message: "an absolute home path is embedded here: portable as a file, broken as behaviour on a different $HOME",
      suggested_fix: "rewrite against ${CODEX_HOME} or the project root at import time",
      auto_fixable: false,
      evidence: "COD §5.9 — [projects.\"<abs>\"], [[skills.config]] path, hook command strings, model_instructions_file, log_dir and sqlite_home all carry absolute paths on the surveyed machine",
    },
    {
      lint_id: "shell_env.default_excludes_disabled",
      severity: "warn",
      applies_to: { kind: "setting", runtime: "codex" },
      predicate: {
        op: "and",
        rules: [
          { op: "value_in", in: "origin.key_path", values: ["shell_environment_policy.ignore_default_excludes"] },
          { op: "value_in", in: "payload.parsed.value", values: [true] },
        ],
      },
      message: "ignore_default_excludes is true, so variables whose names contain KEY, SECRET or TOKEN are forwarded to every spawned shell",
      suggested_fix: "leave ignore_default_excludes at its default and list only the specific variables you need in include_only",
      auto_fixable: false,
      evidence: "COD §4.2 — the default excludes strip names containing KEY/SECRET/TOKEN case-insensitively; disabling them widens the blast radius of every tool call",
    },
    {
      lint_id: "mcp.transport_undocumented",
      severity: "warn",
      applies_to: { kind: "mcp_server", runtime: "codex" },
      predicate: {
        op: "and",
        rules: [
          { op: "has_key", in: "payload.parsed", key: "url" },
          { op: "value_not_in", in: "payload.parsed.type", values: ["http", "streamable-http", "stdio"] },
        ],
      },
      message: "this entry uses a transport Codex 0.144.5 does not document; only stdio and streamable HTTP appear in the manual's MCP section",
      suggested_fix: "emit stdio or streamable HTTP; SSE and ws entries are item-level UNSUPPORTED on this target",
      auto_fixable: false,
      evidence: "COD §4.5, §6.5 — SSE is not mentioned anywhere in the manual's MCP section for this version; presumed dropped, unconfirmed",
    },
  ],

  never_export: [
    {
      rule_id: "codex.auth",
      match: "${CODEX_HOME}/auth.json",
      class: "auth",
      severity: "hard",
      reason: "tokens.id_token / access_token / refresh_token for a live ChatGPT account (COD §4.10 #1)",
    },
    {
      rule_id: "codex.hooks_state",
      match: "${CODEX_HOME}/config.toml#hooks.state",
      class: "trust_state",
      severity: "hard",
      reason: "exporting a trusted_hash launders code-execution trust onto a machine where the user never reviewed the hook — the most security-relevant single line in the Codex research (COD §4.8, §4.10 #2)",
    },
    {
      rule_id: "codex.project_trust",
      match: "${CODEX_HOME}/config.toml#projects",
      class: "trust_state",
      severity: "hard",
      reason: "[projects.\"<abs>\"] trust_level is an absolute local path plus a security decision that must not transfer to a different filesystem (COD §4.10 #4)",
    },
    {
      rule_id: "codex.rules_secret_sink",
      match: "${CODEX_HOME}/rules/*.rules",
      class: "secret_sink",
      severity: "hard",
      reason: "scan-and-refuse, not scan-and-warn: rules record the full argv of every command the user allow-listed, and a live API key was found in one on the first machine examined (COD §5.1). Structure is reported; the bytes never leave.",
    },
    {
      rule_id: "codex.mcp_secret_values",
      match: "${CODEX_HOME}/config.toml#mcp_servers.*.{env,http_headers}",
      class: "secret_sink",
      severity: "soft",
      reason: "values are redacted, KEYS ARE KEPT: the shape of the configuration is the portable part and hiding it would make the bundle lie (manifest §4.3)",
    },
    {
      rule_id: "codex.sessions",
      match: "${CODEX_HOME}/{sessions,archived_sessions}/**",
      class: "conversation_content",
      severity: "hard",
      reason: "181 active and 273 archived rollouts on the surveyed machine; each embeds verbatim conversation, the full base instructions and the absolute cwd (COD §4.12)",
    },
    {
      rule_id: "codex.history",
      match: "${CODEX_HOME}/history.jsonl",
      class: "conversation_content",
      severity: "hard",
      reason: "lines are {session_id, ts, text} — raw prompt text (COD §4.10 #6)",
    },
    {
      rule_id: "codex.sqlite",
      match: "${CODEX_HOME}/*.sqlite",
      class: "conversation_content",
      severity: "hard",
      reason: "logs_*.sqlite (523 MB on the surveyed machine) and memories_*.sqlite index conversation content (COD §4.10 #6, §5.11)",
    },
    {
      rule_id: "codex.memories_store",
      match: "${CODEX_HOME}/memories/**",
      class: "conversation_content",
      severity: "soft",
      reason: "generated summaries of prior chats, secret-adjacent by the manual's own warning; carried only as a hand-reviewed index, never wholesale (COD §4.11)",
    },
    {
      rule_id: "codex.attachments",
      match: "${CODEX_HOME}/attachments/**",
      class: "conversation_content",
      severity: "hard",
      reason: "user-pasted files from prior sessions (COD §4.10 #6)",
    },
    {
      rule_id: "codex.machine_identity",
      match: "${CODEX_HOME}/{.codex-global-state.json,installation_id,chrome-native-hosts*.json}",
      class: "machine_identity",
      severity: "hard",
      reason: "installation identity and native-messaging host registrations (COD §4.10 #6)",
    },
    {
      rule_id: "codex.forced_workspace_id",
      match: "${CODEX_HOME}/config.toml#forced_chatgpt_workspace_id",
      class: "machine_identity",
      severity: "hard",
      reason: "org identifier tied to the source account (COD §4.10 #7)",
    },
    {
      rule_id: "codex.derived_caches",
      match: "${CODEX_HOME}/{models_cache.json,shell_snapshots/**,logs/**}",
      class: "derived",
      severity: "soft",
      reason: "regenerated on first run; log_dir also carries absolute machine paths (COD §4.10 #6)",
    },
    {
      rule_id: "codex.ipc_locks",
      match: "${CODEX_HOME}/{ipc,mcp-oauth-locks}/**",
      class: "machine_local_runtime",
      severity: "hard",
      reason: "process-local sockets and OAuth locks; meaningless off this machine (COD §4.10 #6)",
    },
    {
      rule_id: "codex.plugin_cache",
      match: "${CODEX_HOME}/plugins/cache/**",
      class: "derived",
      severity: "soft",
      reason: "re-resolvable plugin payload; the [plugins] and [marketplaces] declarations are the portable part (COD §4.14)",
    },
  ],
};
